### ISSUE TITLE
Timeout Error OpenAI

### ISSUE THREAD

**Issue by shreyabhadwal** [langchain-ai/langchain#3512] opened 2023-04-25 10:27 UTC
I am facing a Warning similar to the one described here #3005 

`WARNING:langchain.embeddings.openai:Retrying langchain.embeddings.openai.embed_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
`
It just keeps retrying. How do I get around this?

**Comment by dnrico1** [comment] 2023-04-26 18:47
Same for me as well

**Comment by La1c** [comment] 2023-04-27 10:15
Getting the same error, with map-reduce summarizing chain.
Vanilla open ai api works as expected.

**Comment by gabacode** [comment] 2023-04-27 22:26
Same, following 👀

**Comment by shreyabhadwal** [comment] 2023-04-28 05:42
When are y'all getting the error?
For instance, I am getting it through my websocket app deployed on Azure (it's a chatbot application). Weirdly enough, I don't face it when I run the application locally.

**Comment by bkamapantula** [comment] 2023-04-28 11:59
+1

OpenAI chat endpoint always times out when using the summarization chain.

It works with the anthropic endpoint though.

**Comment by Binb1** [comment] 2023-05-02 11:55
+1

@shreyabhadwal Experiencing the exact same behaviour. Local works well but it timeouts on Azure.

**Comment by Binb1** [comment] 2023-05-03 13:57
@shreyabhadwal Strangely enough, every time I deploy a new version of my app it seems to work well. But after a few minutes I get timeouts and I can't really understand why so far. I'm using SSE.
I've tested a lot of different options and I have the same problem doing an Openai python SDK call or Langchain.

**Comment by shreyabhadwal** [comment] 2023-05-03 14:27
@Binb1 I experience the exact same behavior. It works well if I restart the app, and then after a few minutes when I try again I get timeouts. Very weird. 

Interestingly, I have tried doing it without streaming and it seems to be working well. I don't quite understand it.

**Comment by Binb1** [comment] 2023-05-03 14:34
@shreyabhadwal This makes me think that it is more Azure than langchain/openai related then 😕

I have not tried streaming yet as I don't really need it but it fails for me even without it. So strange.

**Comment by gabacode** [comment] 2023-05-03 15:11
Increasing the timeout fixes it for me! Thanks @timothyasp !

**Comment by timothyasp** [comment] 2023-05-05 19:04
openai requests can go as long as 600s, and if you're doing large token
prompts with gpt-4, 300s might be too low. So i'd set it at 600s and hope
for the best.  But i have noticed latencies on OpenAI's end being a lot
higher over the last week or two.


-Tim

**Comment by ColinTitahi** [comment] 2023-05-10 00:56
@shreyabhadwal @Binb1  any luck with Azure?

Same issue local fine and fast, on Azure issues.
Something seems to fall asleep after 4-10 minutes 
For me "Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry" seems to get called **before** the call for chat etc.
After it times out it returns and is good until idle for 4-10 minutes
So Increasing the timeout just increases the wait until it does timeout and calls again.

Driving me nuts and suspect there is a simple configuration I'm missing.

**Comment by shreyabhadwal** [comment] 2023-05-10 06:24
Nope nothing yet
@Binb1 @ColinTitahi are y'all using async calls to OpenAI?

**Comment by ColinTitahi** [comment] 2023-05-10 18:12
@shreyabhadwal  Not explicitly so I don't think so. I'm using generate on the ChatOpenAI so I can get the llm_output token etc and another run call to a chat-conversational-react-description agent with some additional tools. 
These endpoints in my flask app are being called from the client JavaScript which uses async to wait for the response.
It's like something gets set up when the flask app initially starts up and then falls asleep or disconnects or something after say 4-5 minutes and then has to wait for the timeout to occur to reconnect when the user calls it. Hence upping the timeout just increases that initial wait.

**Comment by sagardspeed2** [comment] 2023-05-18 05:41
I am getting same error with model `gpt-4-0314` and max_token = 2048 with request_timeout = 240 in local and live server.
yesterday this was working fine

**Comment by DennisSchwartz** [comment] 2023-05-22 18:23
Same issue here. Running it in a Kubernetes Pod deployed to an AWS cluster and using async calls.
Works perfectly locally but times out as soon as it's in the cluster.

Weirdly, calling the OpenAI LLM directly works, but running the Agent it gets stuck.

This works:
```python
agent_executor = get_agent(user_token)
driver = agent_executor.agent.llm_chain.llm
cl = driver.client()
print(cl.create(model=driver.model_name, prompt='Tell me a poem'))
```

But this does not:
```
await agent_executor.arun(query)
```

**Comment by DennisSchwartz** [comment] 2023-05-22 19:00
Ok so from the comments above I realised I was testing async in one case and blocking in the other.

```
print(await cl.acreate(model=driver.model_name, prompt='Tell me a poem'))
```

Does indeed also time out and fail to run!
So there definitely seems to be an issue with the Async running of OpenAI. I'm going to try Anthropic for now. :)

**Comment by jpsmartbots** [comment] 2023-06-04 12:54
I have the same issue. I am trying to hit completion api on text-davinci-003 engine. I am unable to replicate the issue on my local as it works always. When I containerize and deploy it in AWS Lambda, I get the following error sometimes (dont know when). 
Request timed out: HTTPSConnectionPool(host='smartbotsstudio.openai.azure.com', port=443): Max retries exceeded with url: //openai/deployments/textdavinci003/completions?api-version=2022-12-01 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at XXXX>, 'Connection to <instanceid>.openai.azure.com timed out. (connect timeout=5)')

Any resoultion?

**Comment by maxmarkov** [comment] 2023-06-13 08:21
It could be a problem with the SSL key. Set it up as a system environment variable.
`os.environ["REQUESTS_CA_BUNDLE"] = "PATH_TO_YOUR_CERTIFICATE/YOUR_CERTIFICATE.crt" `

**Comment by flake9** [comment] 2023-08-08 16:51
+1

**Comment by HaochenQ** [comment] 2023-08-30 05:56
I have the same issue. Works well locally but faces timeout issues when the app is deployed to Azure App Service for Linux Python or Custom Container.

**Comment by jpsmartbots** [comment] 2023-08-30 07:25
Hi HaochenQ

May be deploying your solution in a virtual machine might solve your problem. When I moved from AWS Lambda to EC2, the problem got resolved

**Comment by HaochenQ** [comment] 2023-08-31 00:43
> Hi HaochenQ
> 
> May be deploying your solution in a virtual machine might solve your problem. When I moved from AWS Lambda to EC2, the problem got resolved

Thank you@jpsmartbots, I tried to deploy it to fly.io and this issue is gone...

**Comment by ShantanuNair** [comment] 2023-09-20 08:16
Hey all, I believe this being fixed in the openai-python client should also help with this issue, and with generations:

https://github.com/openai/openai-python/pull/387

The async and sync request_timeouts are NOT identical.

**Comment by Pasargaad** [comment] 2023-10-31 11:28
Hi @shreyabhadwal, have you been able to solve this issue?

**Comment by luoqingming110** [comment] 2023-11-22 02:56
same problem

**Comment by ryoung562** [comment] 2023-11-22 05:30
I'm running into the same issue.  i am running a proxy container that talks to openai API works locally, but not when i deploy it to railway.

**Comment by mallapraveen** [comment] 2024-01-25 15:29
did anyone fix this, running into the same issue when I use summarize map reduce chain from Langhian on AWS lambda?

**Closed** 2024-05-10 16:05 UTC

**Comment by lbaiao** [comment] 2024-06-17 23:33
It's 2024 and I'm facing the same issue. 

Using Langchain in a Flask App, hosted in an Azure Web App. Calling Anthropic Claude3 Haiku model in AWS Bedrock.

Langchain request takes about 2 minutes to return. The following ones return smoothly. After about 7 idle minutes, first request takes too long again.

Can't reproduce this issue locally. It only happens in Azure environment.

When testing with boto3 AWS python SDK, the requests return fast every time, with no issues.

**Comment by BwL1289** [comment] 2025-01-28 20:54
Also experiencing. This should be reopened.
