### ISSUE TITLE
I'm using langchain document_loaders to read a PDF, but it's in Hindi, and I'm having trouble understanding it.

### ISSUE THREAD

**Issue by KaifAhmad1** [langchain-ai/langchain#20153] opened 2024-04-08 11:47 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

NA

### Error Message and Stack Trace (if applicable)

NA

### Description

The PDF is actually in Hindi Format and when I am reading it is printing in this language.

```
    
"cht “kks/ku ds fy, Fkhje ¼2 xzke@fdxzk cht½ dk iz;ksx chtksa dks laØfer\ngksus ls cpkus ds fy, djrs gSA DyksjksFkSyksfuy 0-2 izfr”kr ;k eSadkstsc 0-2\nizfr”kr dh nj ls fNM+dko djds izHkkoh jksx fu;a=.k fd;k tk ldrk gSA\nNksVh iÙkh chekjh ¼fyfVy yhQ½ ekbdksIykLek ls gksrh gS tks yhQ gkWij ds\n¼lhfLVl fglheksul½ dkilkbfVl }kjk QSyrh gSA izHkkfor ikS/kk vkdkj esa\nNksVk vkSj ifÙk;ka iSjk NksVh] vfodflr uiqald Qwy tks fd dksbZ Qy dk\n/kkj.k ugh djrhA jksdFkke ds mik; esa fiNsrh Qlyksa dks bdV~Bk djds\nmudks tyk nsuk] “kq:vkrh nkSj ds izHkkfor ikS/kksa dks [ksr ls fudkyuk] rkfd\nfcekjh dk iquZforj.k u gks ik;s vkSj igyh “kq:vkrh y{k.k ds fn[kkbZ nsus ij\neSykfFk;ku 0-2 izfr”kr dh nj fNM+dko djus ls jksx dks fu;af=r fd;k tk\nldrk gSA\niz'u& 4 % mÙkj izns'k ns'k esa fepZ mRiknd {ks=ksa esa ls ,d gS vkSj cgq/kk ge\nfepZ ds iÙkh ds /kCcsnkj jksx dk lkeuk djrs gS] bldk izca/ku dSls\ndjas\\\nmÙkj % iÙkh ds /kCcsnkj jksx tSls ,UFkzksDukst] vYVjusfj;k ldksZLiksjk yhQ LikV vkSj\nyhQ dyZ dkEiysDl bR;kfn chekfj;ka gSa tks fepZ esa yxrh gS\n,UFkSDukst% ;g dksykWbVksVªkbde dSIlkbZ dod ds }kjk QSyrk gSA blds ds\ny{k.k “kq:vkrh nkSj esa u;h Vgfu;ksa ij ¼usØksfll½ Åijh fljs ls uhps dh\nrjQ gfj;kyh foghu fn[kk;h iM+rs gS blfy, bls MkbZcSd Hkh dgrs gSaA Qyksa\nij “kq:vkrh nkSj esa gYds Hkwjs jax ds /kwlj CykbV dh rjg fn[kk;h nsrh gSA\nLkjdksLiksjk yhQ LikV % bl fcekjh ds y{k.k xqykch jax ds xksy /kCcs\nftuds e/; esa Hkwjs jax dk dsUnz gksrk gS ,oa vYVjusfj;k ls izHkkfor ikS/kksa esa\nxgjs Hkwjs jax ds vfuf;er /kCcs ik;s tkrs gS fdUrq nksuksa CykbV ds y{k.k nsj esa\nfn[kk;h iM+rs gSaA\n,aFkszDukst] ldksZLiksjk vkSj vYVjusfj;k yhQ LikV lHkh ds fu;a=.k fy,\nDyksjksFkSyksfuy ¼0-2 izfr”kr½ ,oa eSadkstsc ¼0-2 izfr”kr½ ,d ds ckn 15 fnuksa\nds vUrjky ij fNM+dko djuk pkfg,A\nyhQ dyZ % fepZ esa iÙkh dk xqjpk jksx dbZ dkj.kkas ls gksrk gS tSls fo’kk.kq\neD[kh vkSj fFkzIl ds dkj.k y{k.k eq[;r;k vfodflr >qylh gq;h] [kqjnjh ,oa\neksVh] uhps dh rjQ eqM+h ,oa xqPNs dk vkdkj /kkj.k dj ysrh gSA chekjh ds\nizca/ku ds fy, ikS/ks dh tM+ksa dks bfeMkDyksfizM ¼4 feyh@yhVj ikuh½ esa ,d\n?kaVs ds fy, Mqcksuk pkfg,] ikS/k dks dhVjks/kh tky ds vUnj mxkuk pkfg,]\nvojks/kh Qlyksa ¼eDdk] cktjk] Tokj bR;kfn½ dks yxkuk pkfg, ftlls dhVksa\nds MM+us esa ck/kk mRiUu gksrh gS vkSj le;&le; ij vUrjokgh flLVfed\ndhVuk”kd dk iz;ksx djuk pkfg,A\n44\n"

```

### System Info

pip == 24.0 
python == 3.10.10 
Cuda == 12.1

**Comment by eyurtsev** [comment] 2024-04-08 15:39
This is probably an issue with fonts in the PDF.

However, I'm going to close the issue since there's no way to reproduce, it's unclear what the environment is or which PDF parser is being used.

**Closed by eyurtsev** 2024-04-08 15:39 UTC
Labels: Ɑ: doc loader, 🤖:question
