### ISSUE TITLE
similarity_score_threshold isn't working for MongoDB Atlas Vector Search

### ISSUE THREAD

**Issue by Vishnu-add** [langchain-ai/langchain#18365] opened 2024-03-01 04:37 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

vector_search = MongoDBAtlasVectorSearch.from_connection_string(
    uri,
    DB_NAME + "." + COLLECTION_NAME,
    embeddings,
    index_name=ATLAS_VECTOR_SEARCH_INDEX_NAME,
    relevance_score_fn='cosine',
)

qa_retriever = vector_search.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={'score_threshold': 0.5},
    
)

### Error Message and Stack Trace (if applicable)

 UserWarning: No relevant docs were retrieved using the relevance score threshold 0.5
  warnings.warn()

### Description

I'm trying to use MongoDBAtlasVectorSearch, the similarity_score_threshold is used, but it is always returning an empty list. Only if the score is set to 0.0 then the documents are returned.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.22
> langchain: 0.1.4
> langchain_community: 0.0.19
> langsmith: 0.0.87
> langchain_cli: 0.0.21
> langchain_openai: 0.0.5
> langserve: 0.0.41

**Comment by RemcoGoy** [comment] 2024-03-11 11:38
I'm experiencing the same issue, I've been diving a little bit deeper into this (or at least trying to), and I've also noticed that queries or statements that have nothing to do with the knowledge base, have consistently higher score than relevant queries. Looking at the code, the 'consine' distance is normalized by doing `1 - distance`, but I'm feeling like the "distance" that is returned by MongoDB is already a score, and not the distance. Hence inverting the score to a very low one.

These are all assumptions and I'm looking for someone from LangChain/MongoDB Atlas to confirm these findings for me/us.

**Comment by Honda-a** [comment] 2024-04-08 07:31
I have made a work around for this that any one can implement
```
class FixedMongoDBAtlasVectorSearch(MongoDBAtlasVectorSearch):
    def _similarity_search_with_relevance_scores(
        self,
        query: str,
        k: int = 4,
        **kwargs: Any,
    ) -> list[tuple[Document, float]]:
        docs_and_scores = self.similarity_search_with_score(query, k, **kwargs)
        return docs_and_scores

```

as @RemcoGoy have mentioned above the problem is with the problem is with VectorStore normalizing distance which in case of MongoDB is a score is already a value between 0-1 
it can be fixed by just retruning the score retrieved from MongoDB without doing any normalization on it

**Comment by hveigz** [comment] 2024-04-29 10:49
As per their documentation:
score = (1 + cosine/dot_product(v1,v2)) / 2

https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/#atlas-vector-search-score

**Closed** 2024-08-05 16:08 UTC
Labels: 🤖:bug, Ɑ: retriever, 🔌: mongo

**Comment by SuryaThiru** [comment] 2024-11-11 19:27
Encountered the same issue with cosine similarity in `langchain-mongo`. Are there any plans to fix this issue?

**Comment by agibson-fl** [comment] 2024-12-04 15:50
> As per their documentation: score = (1 + cosine/dot_product(v1,v2)) / 2
> 
> https://www.mongodb.com/docs/atlas/atlas-vector-search/vector-search-stage/#atlas-vector-search-score
> 
> Anyone knows if we can get un-normalized scores from the source instead of this?

I'm having this same problem using the `from langchain_mongodb.vectorstores import MongoDBAtlasVectorSearch` class when using any of the functions that allow you to pass a score_threshold. The default functions seem to work fine. 

I "THINK" the problem is that the "distance" in the base.py implementation of _cosine_relevance_score_fn returns a score out of the mongo query. I "THINK" this function should be overwridden in the MongoDBAtlasVectorSearch implementation.  I "THINK" fixed this in our code:
```
class FixedMongoDBAtlasVectorSearch(MongoDBAtlasVectorSearch):
    def _cosine_relevance_score_fn(self, distance: float) -> float:
        return distance
```
I tested this fix by comparing the average score of the returned documents from the `vector_search.similarity_search_with_score()` call where you cannot pass a threshold (default is .80) verses the average score of the returned documents from the `vector_search.similarity_search_with_relevance_scores()` where you CAN pass the threshold (tested with passing .80) with the above override... and the average score and doc count is exactly the same. This allows me to use the functions and pass a threshold and have it work properly.

I don't KNOW if this is a valid fix as I haven't dived into the langchain code too much to know the real intent of the MongoDBAtlasVectorSearch implementation. But it does seem to return valid scores with the override to `return distance`.
