### ISSUE TITLE
Table 'langchain_pg_collection' is already defined for this MetaData instance.  Specify 'extend_existing=True'

### ISSUE THREAD

**Issue by chaitanya-react** [langchain-ai/langchain#14760] opened 2023-12-15 13:29 UTC
### System Info

langchain: 0.0.39
python: 3.11
OS: MacOS Sonoma 14.2

### Who can help?

@hwchase17 @eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Load two collections using PGVector like this:

collection1 = PGVector.from_existing_index(
    embedding=embeddings,
    collection_name="collection1",
    pre_delete_collection=False,
    distance_strategy=DistanceStrategy.COSINE,
    connection_string=CONNECTION_STRING,
)

collection2 = PGVector.from_existing_index(
    embedding=embeddings,
    collection_name="collection1",
    pre_delete_collection=False,
    distance_strategy=DistanceStrategy.COSINE,
    connection_string=CONNECTION_STRING,
)

`collection1` works fine, but while initializing collection2, I get the error 
`Table 'langchain_pg_collection' is already defined for this MetaData instance.  Specify 'extend_existing=True'`

![image](https://github.com/langchain-ai/langchain/assets/108780317/9271096e-d246-4ebf-9978-74cef82c3fe9)

Setting `extend_existing=True` doesn't seem to work - I think this is a SQLAlchemy error.

### Expected behavior

The above code should just work without error.
This was working in previous versions: 0.0.310 this code works, but shows an error in 0.0.390.
If there are multiple connections happening to the index, then the documentation doesn't talk about how to handle multiple connections.

**Comment by efriis** [comment] 2023-12-15 18:19
Should be fixed in next release due to #14726

**Closed by efriis** 2023-12-15 18:19 UTC
Labels: area: vector store, auto:bug

**Comment by shlomi-schwartz** [comment] 2024-01-02 12:48
I still have this issue on langchain==0.0.353 was this fix pushed?

**Comment by deniercounter** [comment] 2024-01-03 09:09
@shlomi-schwartz I can confirm that this is NOT solved with:

```zsh
$ pip list | grep langchain
langchain                 0.0.353
langchain-community       0.0.3
langchain-core            0.1.4
langchain-experimental    0.0.25
```

with
```zsh
$ python3 -V               
Python 3.9.18
```

But this solves the problem as mentioned above:

```python
__table_args__ = {'extend_existing': True}
```
