### ISSUE TITLE
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (/usr/local/lib/python3.11/site-packages/langchain_core/tracers/context.py

### ISSUE THREAD

**Issue by adarshkrpf** [langchain-ai/langchain#15526] opened 2024-01-04 08:08 UTC
### System Info

0.0.352 and 0.0.353

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

Custom _call wrapper

### Expected behavior

No import error

**Comment by Abdullahw72** [comment] 2024-01-04 09:43
Facing same issue even though I did not change anything in my running code.

**Comment by xkaiDu** [comment] 2024-01-04 10:20
Found the issue:
In commit [7eec8f2](https://github.com/langchain-ai/langchain/commit/7eec8f24876fd624573c09ff82270362031e6a5f#) the function [tracing_enabled](https://github.com/langchain-ai/langchain/commit/7eec8f24876fd624573c09ff82270362031e6a5f#diff-aa3d4ef71b404ecd0d1198ccf778a3ccc605d9b6e043057d0db3bd8f7d9c483dL46) was deleted, see [#15326](https://github.com/langchain-ai/langchain/pull/15326)

The commit itself handled the lingering dependencies correctly. however, the function deletion was included in langchain-core [0.1.5](https://github.com/langchain-ai/langchain/pull/15480), and is being referred to by v0.0.353, which didn't clean up the dependencies yet, not until 0.0.354

I haven't tried yet, but upgrading to 0.0.354 should resolve the issue.
And 0.0.353 should have dependencies for langchain-core <=0.1.4

**Comment by baskaryan** [comment] 2024-01-04 19:45
As @xkaiDu mentioned, this issue was caused by an incompatibility between older versions of `langchain`, meaning those <0.0.354, and `langchain-core==0.1.5`. If you have `langchain>=0.0.354` this should not be an issue.

We've fixed this issue in `langchain-core==0.1.6`.

So to resolve, either:
- Update `langchain` to >=0.0.354
- Or, if you'd like to stay pinned to an older version of `langchain`, update just `langchain-core` to a version >=0.1.6

Closing issue, but if the above don't work for anyone please let us know!

**Closed by baskaryan** 2024-01-04 19:45 UTC
Labels: auto:bug

**Comment by hwchase17** [comment] 2024-01-04 19:50
We've also yanked 0.1.5
