### ISSUE TITLE
json parser failed to parse full text if text startes with a number

### ISSUE THREAD

**Issue by spsingh559** [langchain-ai/langchain#23960] opened 2024-07-08 08:12 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    def custom_parser(self, inputs: AIMessage):
        output = {"answer": None}
        try:
            json_parser = JsonOutputParser(pydantic_object=JsonOutputParserModel)
            json_output = json_parser.parse(inputs.content)  # type: ignore
            print('json_output',json_output)
            output["answer"] = json_output.get("answer", None)
   
        except (json.JSONDecodeError, OutputParserException) as e:
            parser = StrOutputParser()
            str_output = parser.invoke(inputs.content)  # type: ignore
            output["answer"] = str_output
        except Exception as e:
            print(f"Custom Parsing Error :{e}")

        return output

### Error Message and Stack Trace (if applicable)

json_output 90
Custom Parsing Error :'int' object has no attribute 'get'

### Description

I am trying to use langchain json parsing lib to parse a text into json.
Input of the custom_parser is model response : AI message, function checks if the respnse can be parse as json then try block will be executed and it the message can't be parsed as json, then JSON Decode Error block will be executed. The function is written in such a way that it can handle plain string as response or stringify json.

Issue is when i pass a string message:

`custom_parser("90. Yes, you need to file the dispute")`
output is:

json_output 90
Custom Parsing Error :'int' object has no attribute 'get'

But if i pass string message without number then it goes to second block and code get executed as usual
`custom_parser(" Yes, you need to file the dispute")`
Output:
{'answer': 'you need to file the dispute'}

### System Info

langchain==0.2.0
langchain-community==0.2.0
langchain-core==0.2.1
langchain-openai==0.1.7
langchain-text-splitters==0.2.0

**Comment by eyurtsev** [comment] 2024-07-10 14:44
@spsingh559 could you provide a minimal reproducible example? From the report it looks more likely that there's a bug in the custom code than with the library.

**Comment by eyurtsev** [comment] 2024-07-10 14:44
I'm going to close the issue for now -- feel free to re-open if you're able to provide a minimal reproducible example

**Closed by eyurtsev** 2024-07-10 14:44 UTC
Labels: 🤖:bug

**Comment by tibor-reiss** [comment] 2024-07-10 19:06
Hi @spsingh559, none of the strings passed are is in json format, so it's not surprising that it is not working. If one steps through the code, one can see that the program flow is different:
- in the first case, after subtracting the characters it ends up with "90" which is parseable (try it out: `json.loads("90")`), but it just returns the integer instead of a dict. By adding AttributeError to the list of exceptions, one would also end up with calling the StrOutputParser.
- in the second case, none of the parts is parseable, thus it throws a OutputParserException which is caught and then the StrOutputParser is used.

Furthermore, the documentation clearly states that the LLM has to fulfill some conditions, see: https://python.langchain.com/v0.2/docs/how_to/output_parser_json/

Some notes:
- the description is missing the python version
- please try to use the latest version of the library, because this is a project which evolves fast (and is still in beta)
- the MCVE is not "complete": it is missing the imports, the main function and most importantly the `JsonOutputParserModel`. Additionally, the way how you called `custom_parser` would just fail because there is a `self` argument. I just used None for it, but it suggests that you might have even more (for the MCVE unrelevant) logic.
