### ISSUE TITLE
chain.ainvoke() will result in streaming output

### ISSUE THREAD

**Issue by Huarong** [langchain-ai/langchain#20980] opened 2024-04-28 06:41 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

no at the moment

### Description

In langraph we use chain.ainvoke() in inner node and  app.astream_events() for the whole graph app.  But we found out that the chain.ainvoke() output streaming tokens.

We I dived into the code, and found maybe because of the following code:

https://github.com/langchain-ai/langchain/blob/804390ba4bcc306b90cb6d75b7f01a4231ab6463/libs/core/langchain_core/language_models/chat_models.py#L684-L701

`type(self)._astream` is `ChatOpenAI._astream`
`kwargs` is a empty {}, which dose not have `stream` key from params.
The langgraph app have a `LogStreamCallbackHandler` in the run_manager.handlers.
So the `if statement` is `True` and the code generated streaming output which is not expected.

May be you should add key 'stream' to `kwargs` from `params`. And I have tried it solved my problem.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
> Python Version:  3.11.2 (main, Feb 21 2024, 12:24:36) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.1.46
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.22
> langchain_openai: 0.0.6
> langchain_text_splitters: 0.0.1
> langgraph: 0.0.39

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by eyurtsev** [comment] 2024-04-29 16:56
AFAIK it's only turned on when is `stream` = True -- which forces the model to stream even when using `ainvoke`.

This is not a bug, but the current way by which the model interface works.

**Comment by Huarong** [comment] 2024-04-30 02:32
> AFAIK

@eyurtsev But I didn't set `stream=True`. Actually, stream is False in LLM, but it isn't passed to `kwargs`.
I just called `astream_events()` in langgraph app, and it seems make all the calls of all chains streaming. So how can I use non stream in some intermediate chains which using `ainvoke`?

**Comment by eyurtsev** [comment] 2024-04-30 14:48
```python
from langchain_core.runnables import chain

model = ChatOpenAI()

@chain
async def thingy(inputs):
  return model.ainvoke(inputs['prompt'])

async for event in thingy.astream_events({}):
   print(event)
```

The model should be invoked with ainvoke

**Comment by Huarong** [comment] 2024-05-07 07:56
> ```python
> from langchain_core.runnables import chain
> 
> model = ChatOpenAI()
> 
> @chain
> async def thingy(inputs):
>   return model.ainvoke(inputs['prompt'])
> 
> async for event in thingy.astream_events({}):
>    print(event)
> ```
> 
> The model should be invoked with ainvoke

@eyurtsev The model in the code is invoked with `astream` instead of `ainvoke`.

The code:
```python
import asyncio
from langchain_core.runnables import chain
from langchain_openai import ChatOpenAI

model = ChatOpenAI()

@chain
async def thingy(inputs):
    return await model.ainvoke(inputs["prompt"])


async def main():
    async for event in thingy.astream_events({"prompt": "hello"}, version="v1"):
        print(event)


if __name__ == "__main__":
    asyncio.run(main())
```

The output:
```
{'event': 'on_chain_start', 'run_id': '06beb82d-5097-4fec-b731-4fc2c98ace91', 'name': 'thingy', 'tags': [], 'metadata': {}, 'data': {'input': {'prompt': 'hello'}}}
{'event': 'on_chat_model_start', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='Hello', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='!', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' How', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' can', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' I', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' assist', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' you', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' today', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='?', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chat_model_end', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}, 'output': {'generations': [[{'text': 'Hello! How can I assist you today?', 'generation_info': {'finish_reason': 'stop'}, 'type': 'ChatGeneration', 'message': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}]], 'llm_output': None, 'run': None}}}
{'event': 'on_chain_stream', 'run_id': '06beb82d-5097-4fec-b731-4fc2c98ace91', 'tags': [], 'metadata': {}, 'name': 'thingy', 'data': {'chunk': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
{'event': 'on_chain_end', 'name': 'thingy', 'run_id': '06beb82d-5097-4fec-b731-4fc2c98ace91', 'tags': [], 'metadata': {}, 'data': {'output': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
```

The versions:
```
(.venv) ➜  latest_langchain python -m langchain_core.sys_info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
> Python Version:  3.11.2 (main, Feb 21 2024, 12:24:36) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.1.52
> langchain: 0.1.17
> langchain_community: 0.0.37
> langsmith: 0.1.54
> langchain_openai: 0.1.6
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by Huarong** [comment] 2024-07-04 04:19
> > ```python
> > from langchain_core.runnables import chain
> > 
> > model = ChatOpenAI()
> > 
> > @chain
> > async def thingy(inputs):
> >   return model.ainvoke(inputs['prompt'])
> > 
> > async for event in thingy.astream_events({}):
> >    print(event)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The model should be invoked with ainvoke
> 
> @eyurtsev The model in the code is invoked with `astream` instead of `ainvoke`.
> 
> The code:
> 
> ```python
> import asyncio
> from langchain_core.runnables import chain
> from langchain_openai import ChatOpenAI
> 
> model = ChatOpenAI()
> 
> @chain
> async def thingy(inputs):
>     return await model.ainvoke(inputs["prompt"])
> 
> 
> async def main():
>     async for event in thingy.astream_events({"prompt": "hello"}, version="v1"):
>         print(event)
> 
> 
> if __name__ == "__main__":
>     asyncio.run(main())
> ```
> 
> The output:
> 
> ```
> {'event': 'on_chain_start', 'run_id': '06beb82d-5097-4fec-b731-4fc2c98ace91', 'name': 'thingy', 'tags': [], 'metadata': {}, 'data': {'input': {'prompt': 'hello'}}}
> {'event': 'on_chat_model_start', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='Hello', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='!', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' How', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' can', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' I', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' assist', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' you', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content=' today', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='?', id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'chunk': AIMessageChunk(content='', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chat_model_end', 'name': 'ChatOpenAI', 'run_id': '55e39a9b-b791-4d5b-b381-ca7d93371515', 'tags': [], 'metadata': {}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}, 'output': {'generations': [[{'text': 'Hello! How can I assist you today?', 'generation_info': {'finish_reason': 'stop'}, 'type': 'ChatGeneration', 'message': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}]], 'llm_output': None, 'run': None}}}
> {'event': 'on_chain_stream', 'run_id': '06beb82d-5097-4fec-b731-4fc2c98ace91', 'tags': [], 'metadata': {}, 'name': 'thingy', 'data': {'chunk': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> {'event': 'on_chain_end', 'name': 'thingy', 'run_id': '06beb82d-5097-4fec-b731-4fc2c98ace91', 'tags': [], 'metadata': {}, 'data': {'output': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop'}, id='run-55e39a9b-b791-4d5b-b381-ca7d93371515')}}
> ```
> 
> The versions:
> 
> ```
> (.venv) ➜  latest_langchain python -m langchain_core.sys_info
> 
> System Information
> ------------------
> > OS:  Darwin
> > OS Version:  Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
> > Python Version:  3.11.2 (main, Feb 21 2024, 12:24:36) [Clang 15.0.0 (clang-1500.1.0.2.5)]
> 
> Package Information
> -------------------
> > langchain_core: 0.1.52
> > langchain: 0.1.17
> > langchain_community: 0.0.37
> > langsmith: 0.1.54
> > langchain_openai: 0.1.6
> > langchain_text_splitters: 0.0.1
> 
> Packages not installed (Not Necessarily a Problem)
> --------------------------------------------------
> The following packages were not found:
> 
> > langgraph
> > langserve
> ```

@eyurtsev Do you reproduce the issue?

**Comment by eyurtsev** [comment] 2024-08-13 19:01
Hi @Huarong, apologies my initial response here was incorrect -- the functionality was added intentionally to force a chat model to stream if invoked within a .stream() context.

Why is the fact that the chat model streaming a problem in your case? The code is using astream_events() after all so being able so what's the problem with token by token output?

**Comment by eyurtsev** [comment] 2024-08-13 19:31
Newest core allows disabling streaming explicitly using this attribute: https://github.com/langchain-ai/langchain/blob/089f5e6cad4092185798a045c39c017ae790a8f2/libs/core/langchain_core/language_models/chat_models.py#L224-L224

**Comment by Huarong** [comment] 2024-08-14 02:01
> Hi @Huarong, apologies my initial response here was incorrect -- the functionality was added intentionally to force a chat model to stream if invoked within a .stream() context.
> 
> Why is the fact that the chat model streaming a problem in your case? The code is using astream_events() after all so being able so what's the problem with token by token output?

I have described the issue here: https://github.com/langchain-ai/langchain/pull/25340#issuecomment-2287661860
Thanks for your reply.

**Comment by Huarong** [comment] 2024-08-14 02:14
I found another thing which I'm not sure if it is a bug or I missed something. The behaviors of the test scripts are different between python 3.9.15 and python  3.11.2 while the other system infos are the same. Please have a look. @eyurtsev 

test code
```
import asyncio
from langchain_core.runnables import chain
from langchain_openai import ChatOpenAI

model = ChatOpenAI()

@chain
async def thingy(inputs):
    return await model.ainvoke(inputs["prompt"])


async def main():
    async for event in thingy.astream_events({"prompt": "hello"}, version="v1"):
        print(event)


if __name__ == "__main__":
    asyncio.run(main())
```
python 3.9.15 result
```
{'event': 'on_chain_start', 'run_id': '22c4b0ea-a33c-41ac-809c-b040caf90a46', 'name': 'thingy', 'tags': [], 'metadata': {}, 'data': {'input': {'prompt': 'hello'}}, 'parent_ids': []}
{'event': 'on_chain_stream', 'run_id': '22c4b0ea-a33c-41ac-809c-b040caf90a46', 'tags': [], 'metadata': {}, 'name': 'thingy', 'data': {'chunk': AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-e0412db6-4e9f-4e7c-a6bc-5c782f200048-0', usage_metadata={'input_tokens': 8, 'output_tokens': 9, 'total_tokens': 17})}, 'parent_ids': []}
{'event': 'on_chain_end', 'name': 'thingy', 'run_id': '22c4b0ea-a33c-41ac-809c-b040caf90a46', 'tags': [], 'metadata': {}, 'data': {'output': AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 8, 'total_tokens': 17}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None}, id='run-e0412db6-4e9f-4e7c-a6bc-5c782f200048-0', usage_metadata={'input_tokens': 8, 'output_tokens': 9, 'total_tokens': 17})}, 'parent_ids': []}
```

python 3.11.2 result
```
{'event': 'on_chain_start', 'run_id': 'f265dcdd-8cc9-4f93-9281-3c64fd57ea36', 'name': 'thingy', 'tags': [], 'metadata': {}, 'data': {'input': {'prompt': 'hello'}}, 'parent_ids': []}
{'event': 'on_chat_model_start', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='Hello', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='!', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' How', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' can', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' I', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' assist', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' you', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content=' today', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='?', id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_stream', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'chunk': AIMessageChunk(content='', response_metadata={'finish_reason': 'stop', 'model_name': 'gpt-3.5-turbo-0125'}, id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chat_model_end', 'name': 'ChatOpenAI', 'run_id': 'dc307e75-a572-4116-8e8b-d8364c7fcaae', 'tags': [], 'metadata': {'ls_provider': 'openai', 'ls_model_name': 'gpt-3.5-turbo', 'ls_model_type': 'chat', 'ls_temperature': 0.7}, 'data': {'input': {'messages': [[HumanMessage(content='hello')]]}, 'output': {'generations': [[{'text': 'Hello! How can I assist you today?', 'generation_info': {'finish_reason': 'stop', 'model_name': 'gpt-3.5-turbo-0125'}, 'type': 'ChatGeneration', 'message': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop', 'model_name': 'gpt-3.5-turbo-0125'}, id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}]], 'llm_output': None, 'run': None}}, 'parent_ids': []}
{'event': 'on_chain_stream', 'run_id': 'f265dcdd-8cc9-4f93-9281-3c64fd57ea36', 'tags': [], 'metadata': {}, 'name': 'thingy', 'data': {'chunk': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop', 'model_name': 'gpt-3.5-turbo-0125'}, id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
{'event': 'on_chain_end', 'name': 'thingy', 'run_id': 'f265dcdd-8cc9-4f93-9281-3c64fd57ea36', 'tags': [], 'metadata': {}, 'data': {'output': AIMessage(content='Hello! How can I assist you today?', response_metadata={'finish_reason': 'stop', 'model_name': 'gpt-3.5-turbo-0125'}, id='run-dc307e75-a572-4116-8e8b-d8364c7fcaae')}, 'parent_ids': []}
```
python 3.9.15 system info:
```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
> Python Version:  3.9.15 (main, Apr 13 2023, 10:22:33)
[Clang 14.0.0 (clang-1400.0.29.202)]

Package Information
-------------------
> langchain_core: 0.2.30
> langchain: 0.2.13
> langsmith: 0.1.99
> langchain_openai: 0.1.21
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.3
> async-timeout: 4.0.3
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.40.6
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2
```
python 3.11.2 system info:
```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103
> Python Version:  3.11.2 (main, Feb 21 2024, 12:24:36) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.2.30
> langchain: 0.2.13
> langsmith: 0.1.99
> langchain_openai: 0.1.21
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.3
> async-timeout: 4.0.3
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.40.6
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2
```
system info diff
![image](https://github.com/user-attachments/assets/1cea8e98-ff15-4a26-a0c2-b92ca51698fa)

**Comment by eyurtsev** [comment] 2024-08-14 13:53
Yes, that's a known issue due to a feature that doesn't exist in asyncio with python <= 3.10. 

See second warning here:

https://python.langchain.com/v0.2/docs/how_to/callbacks_async/

And warning here:

https://python.langchain.com/v0.2/docs/concepts/#passing-callbacks

We should probably document these even better.

If you're using python <= 3.10, you're responsible for propagating the callbacks.


Do something like this:

```python
from langchain_core.runnables import RunnableLambda, chain, RunnableGenerator

@chain
async def goo(inputs, config):
    print(config)
    return inputs


@chain
async def foo(inputs, config):
    print(config)
    return await goo.ainvoke(inputs, config)
    
await foo.ainvoke({'x': 2})

async for event in foo.astream_events('h', version='v2'):
    print(event)
````

Closing the issue for now.

**Comment by eyurtsev** [comment] 2024-08-14 13:53
@Huarong if the second problem is still not resolved, could you open a separate issue for it?

**Closed by eyurtsev** 2024-08-14 13:53 UTC
Labels: Ɑ:  core
