### ISSUE TITLE
Bug after the openai updated in Embedding

### ISSUE THREAD

**Issue by SGA-Yuze-Li** [langchain-ai/langchain#13051] opened 2023-11-08 07:56 UTC
### System Info

AWS Sagemaker DataScience3.0 Image.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

here is my code, it worked before Nov 7th.

`Chroma.from_documents(documents=document, embedding=embeddings,)`

Then i get this error:
`ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023 `

### Expected behavior

Is anyone know how to fix this?

**Comment by 95** [comment] 2023-11-08 07:59
I've had this exact issue as well. https://github.com/langchain-ai/langchain/issues/13050
Hoping for a resolution

**Comment by thundo** [comment] 2023-11-08 09:24
Same error on Colab with openai pinning to `0.28.1`

**Comment by 95** [comment] 2023-11-08 09:27
> Same error on Colab with openai pinning to `0.28.1`

Yes. I pinned to 0.28.1 as well, didn't help.

**Comment by sjoerd222888** [comment] 2023-11-08 09:59
Problem seems to appear with chroma update to [0.4.16](https://pypi.org/project/chromadb/)

Pinning to previous version seems to help. 

```
chromadb==0.4.15
```

Langchain still implements the old interface. See: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

**Comment by pa1kumar9** [comment] 2023-11-08 10:02
> Problem seems to appear with chroma update to [0.4.16](https://pypi.org/project/chromadb/)
> 
> Pinning to previous version seems to help.
> 
> ```
> chromadb==0.4.15
> ```
> This worked.,, Thank you

**Comment by 95** [comment] 2023-11-08 10:07
> Problem seems to appear with chroma update to [0.4.16](https://pypi.org/project/chromadb/)
> 
> Pinning to previous version seems to help.
> 
> ```
> chromadb==0.4.15
> ```
> 
> Langchain still implements the old interface. See: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

Worked perfectly. Thank you

**Comment by itsvaibhav01** [comment] 2023-11-08 10:32
> Problem seems to appear with chroma update to [0.4.16](https://pypi.org/project/chromadb/)
> 
> Pinning to previous version seems to help.
> 
> ```
> chromadb==0.4.15
> ```
> 
> Langchain still implements the old interface. See: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

Thanks a lot!!!

**Comment by SGA-Yuze-Li** [comment] 2023-11-08 10:44
> Problem seems to appear with chroma update to [0.4.16](https://pypi.org/project/chromadb/)
> 
> Pinning to previous version seems to help.
> 
> ```
> chromadb==0.4.15
> ```
> 
> Langchain still implements the old interface. See: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

Thanks a lot! Worked!

**Comment by Kozato01** [comment] 2023-11-08 14:14
> O problema parece aparecer com a atualização do chroma para [0.4.16](https://pypi.org/project/chromadb/)
> 
> Fixar na versão anterior parece ajudar.
> 
> ```
> chromadb==0.4.15
> ```
> 
> Langchain ainda implementa a interface antiga. Consulte: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

My hero!

**Comment by efriis** [comment] 2023-11-08 21:39
Langchain 0.0.332 released with the chroma team's fix for compatibility with chromadb>=0.4.16

Can now use latest of both `pip install -U langchain chromadb`

**Closed by efriis** 2023-11-08 21:39 UTC
Labels: area: embeddings, auto:bug, integration: chroma

**Comment by ScottXiao233** [comment] 2023-11-09 06:13
chromadb-0.4.16 langchain-0.0.332
```
from langchain.document_loaders import TextLoader
loader = TextLoader('/tanglg/lx/code/Qwen/forest_file.txt')
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)
 
embeddings = OpenAIEmbeddings(
    openai_api_key="EMPTY",
    openai_api_base="http://localhost:8000/v1", 
)

forest_file_store = Chroma.from_documents(documents=texts, embedding=embeddings, collection_name="forest_file")
```
still got the same question~
 ```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb 单元格 3 line 1
      [5](vscode-notebook-cell://ssh-remote%2B172.30.254.229/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb#W1sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4) texts = text_splitter.split_documents(documents)
      [7](vscode-notebook-cell://ssh-remote%2B172.30.254.229/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb#W1sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6) embeddings = OpenAIEmbeddings(
      [8](vscode-notebook-cell://ssh-remote%2B172.30.254.229/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb#W1sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7)     openai_api_key="EMPTY",
      [9](vscode-notebook-cell://ssh-remote%2B172.30.254.229/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb#W1sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8)     openai_api_base="http://localhost:8000/v1", 
     [10](vscode-notebook-cell://ssh-remote%2B172.30.254.229/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb#W1sdnNjb2RlLXJlbW90ZQ%3D%3D?line=9) )
---> [12](vscode-notebook-cell://ssh-remote%2B172.30.254.229/tanglg/lx/code/Qwen/xly_vectordb_test.ipynb#W1sdnNjb2RlLXJlbW90ZQ%3D%3D?line=11) forest_file_store = Chroma.from_documents(documents=texts, embedding=embeddings, collection_name="forest_file")

File /tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:684, in Chroma.from_documents(cls, documents, embedding, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    [682](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:682) texts = [doc.page_content for doc in documents]
    [683](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:683) metadatas = [doc.metadata for doc in documents]
--> [684](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:684) return cls.from_texts(
    [685](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:685)     texts=texts,
    [686](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:686)     embedding=embedding,
    [687](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:687)     metadatas=metadatas,
    [688](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:688)     ids=ids,
    [689](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:689)     collection_name=collection_name,
    [690](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:690)     persist_directory=persist_directory,
    [691](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:691)     client_settings=client_settings,
    [692](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:692)     client=client,
    [693](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:693)     collection_metadata=collection_metadata,
    [694](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:694)     **kwargs,
    [695](https://vscode-remote+ssh-002dremote-002b172-002e30-002e254-002e229.vscode-resource.vscode-cdn.net/tanglg/commonsoft/miniconda3/envs/qwen/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:695) )
...

ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023
```

**Comment by TimCoates** [comment] 2023-11-09 13:14
I'm getting this bug with:
langchain V 0.0.332
chromadb V 0.4.16


```
persist_directory='./db'
from langchain.embeddings import GPT4AllEmbeddings
embedding=GPT4AllEmbeddings()
from langchain.vectorstores import Chroma
vectordb = Chroma.from_documents(documents=texts,
                                 embedding=embedding,
                                 persist_directory=persist_directory)
```

**Comment by efriis** [comment] 2023-11-09 18:32
@ScottXiao233 - I tried reproducing, but your code works for me. If you're using a custom openai embeddings endpoint, maybe make sure it works with the new sdk alone? 

@TimCoates - This also might be something with your local embeddings setup. Maybe submit as a new issue specific to GPT4AllEmbeddings? It's unclear to me why you'd see this using something other than OpenAI

**Comment by afedotov-align** [comment] 2023-11-14 15:23
@efriis , also doesn't work for me with 
langchain==0.0.335
chromadb==0.4.17

code example
```
embeddings = AzureOpenAIEmbeddings(
    model="text-embedding-ada-002",
    deployment=os.getenv("EMBEDDING_DEPLOYMENT_NAME"),
    azure_endpoint=os.getenv("AZURE_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_KEY"),
    openai_api_version=os.getenv("AZURE_API_VERSION"),
)

persistent_client = chromadb.PersistentClient("./test")

collection = persistent_client.get_or_create_collection(
    name="test", embedding_function=embeddings.embed_documents
)

**Comment by efriis** [comment] 2023-11-14 17:35
@afedotov-align - looks like you might be mixing LangChain `langchain.vectorstores.Chroma` with directly accessing `chromadb`. Could you try again using the LangChain vectorstore with the LangChain embedding function? https://python.langchain.com/docs/integrations/vectorstores/chroma#basic-example

**Comment by TimCoates** [comment] 2023-11-14 20:03
> @ScottXiao233 - I tried reproducing, but your code works for me. If you're using a custom openai embeddings endpoint, maybe make sure it works with the new sdk alone?
> 
> @TimCoates - This also might be something with your local embeddings setup. Maybe submit as a new issue specific to GPT4AllEmbeddings? It's unclear to me why you'd see this using something other than OpenAI

Thanks, rather than using .from_documents, doing as so:
`vectorstore = Chroma("langchain_store", embedding_function=embeddings, persist_directory="./db")`
Then:
`Chroma.add_documents(vectorstore. texts)`
worked for me

**Comment by shreyahegde18** [comment] 2023-11-21 07:33
> Problem seems to appear with chroma update to [0.4.16](https://pypi.org/project/chromadb/)
> 
> Pinning to previous version seems to help.
> 
> ```
> chromadb==0.4.15
> ```
> 
> Langchain still implements the old interface. See: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

Thank you :')

**Comment by varayush007** [comment] 2024-02-25 19:24
I am getting this error while using 
vectorstore = Chroma.from_texts(
        to_vectorize,
        embedding=embeddings,
        metadatas=few_shots
    )


ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs']) Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface. Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

Im using chromadb==0.4.15

**Comment by amanlai** [comment] 2024-02-25 22:47
@varayush007 Try defining a custom class that sub-classes `OpenAIEmbeddings` and use it as the embedding function. [This discussion](https://stackoverflow.com/q/77925185/19123103) may help.

**Comment by BlackSiao** [comment] 2024-03-01 09:47
> chromadb==0.4.15
pip install chromaab=0.4.15 really solve my promblem, thank you

**Comment by kaisersoser** [comment] 2024-04-02 12:17
Backdating my chromadb version to chromadb==0.4.15 worked for me.
Just run the command: pip install --upgrade chromadb==0.4.15
