### ISSUE TITLE
[Embedding] The dimensions parameter of OpenAIEmbeddings is not working

### ISSUE THREAD

**Issue by ZhangShenao** [langchain-ai/langchain#24378] opened 2024-07-18 02:11 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import os

import dotenv
from langchain_openai import OpenAIEmbeddings

dotenv.load_dotenv()

embeddings = OpenAIEmbeddings(
    model='text-embedding-3-large',
    dimensions=1024,  # assign dimensions to 1024
    openai_api_base=os.getenv('OPENAI_API_BASE')
)

text = 'This is a test document.'
vector = embeddings.embed_documents([text])
print(f'the dimension of vector is {len(vector[0])}')
```

Output:
the dimension of vector is 3072

### Description

- I'm using OpenAIEmbeddings to embed my document.
- I assign model to text-embedding-3-large and dimension to 1024
- However, the actual dimension of vector is still 3072(default with text-embedding-3-large)
- It seems that the param `dimension` is not working.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
> Python Version:  3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.2.20
> langchain: 0.2.8
> langchain_community: 0.2.7
> langsmith: 0.1.82
> langchain_experimental: 0.0.62
> langchain_huggingface: 0.0.3
> langchain_openai: 0.1.14
> langchain_text_splitters: 0.2.2

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by baskaryan** [comment] 2024-07-18 02:51
hm I'm not able to reproduce. Are you actually using OpenAI or some openai-like API?

![Screenshot 2024-07-17 at 7 50 54 PM](https://github.com/user-attachments/assets/59149243-50bc-45d4-aebf-e63e886d7389)

**Comment by ZhangShenao** [comment] 2024-07-18 03:39
> hm I'm not able to reproduce. Are you using OpenAI or some openai-like API?
> 
> ![Screenshot 2024-07-17 at 7 50 54 PM](https://private-user-images.githubusercontent.com/22008038/349764880-59149243-50bc-45d4-aebf-e63e886d7389.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzQxNDcsIm5iZiI6MTcyMTI3Mzg0NywicGF0aCI6Ii8yMjAwODAzOC8zNDk3NjQ4ODAtNTkxNDkyNDMtNTBiYy00NWQ0LWFlYmYtZTYzZTg4NmQ3Mzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDAzMzcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNWEwNjU3YTNmYjA3YTIwYzY1ZTZlMTExZWViNDg4NzNkNDVhM2QxZDhiNjQ0ZTk5ZjE4ZjhmODYyZWM5N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hedSvy7zo4G8UGBMcZypAvPFUEHmRRkFb150p7ARqYo)

I'm using an open-ai like API, may be there's some problem in this agent. I'll check it, thank you for your answer.

**Comment by baskaryan** [comment] 2024-07-18 20:56
closing for now, @ZhangShenao please feel free to reopen if the issue does seem to be with the langchain integration

**Closed by baskaryan** 2024-07-18 20:56 UTC
Labels: Ɑ: embeddings, 🤖:bug, 🔌: openai

**Comment by ZhangShenao** [comment] 2024-07-19 01:10
> closing for now, @ZhangShenao please feel free to reopen if the issue does seem to be with the langchain integration

OK, thanks!
