### ISSUE TITLE
Issue with user_agent error when creating a CohereReRank object in LangChain 

### ISSUE THREAD

**Issue by iammehdii** [langchain-ai/langchain#13058] opened 2023-11-08 12:38 UTC
### System Info

last version of langchain and cohere

### Who can help?

@@agola11
I am encountering an error related to the user_agent when attempting to create a CohererRank object in the LangChain p. I have verified that I am passing a valid cohere_api_key and can successfully use the rerank function from Cohere directly. However, when trying to utilize it through the LangChain project, I encounter this specific issue related to the user_agent.

[/usr/local/lib/python3.10/dist-packages/langchain/retrievers/document_compressors/cohere_rerank.py](https://localhost:8080/#) in validate_environment(cls, values)
     53             values, "cohere_api_key", "COHERE_API_KEY"
     54         )
---> 55         client_name = values["user_agent"]
     56         values["client"] = cohere.Client(cohere_api_key, client_name=client_name)
     57         return values

KeyError: 'user_agent'

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import os
import getpass

os.environ["COHERE_API_KEY"] = getpass.getpass("Cohere API Key:")
from langchain.llms import OpenAI
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CohereRerank
compressor = CohereRerank()

### Expected behavior

i want to create an object of CohereReRank.

**Comment by gardner** [comment] 2023-11-25 08:19
Please close. This is a duplicate of https://github.com/langchain-ai/langchain/issues/12899

**Closed** 2024-03-13 19:58 UTC
Labels: 🤖:bug, Ɑ:  models
