### ISSUE TITLE
returning an error like LineList expected dict not int (type=type_error) while using MultiQueryRetriever

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17336] opened 2024-02-09 19:18 UTC
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Idea or request for content:

below's the code which i tried running

```
retriever = MultiQueryRetriever.from_llm(retriever=vectorStore.as_retriever(), llm=llm)

docs = retriever.get_relevant_documents(query="data related to cricket?")
```

below's the output

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py](https://localhost:8080/#) in parse_obj(cls, obj)
    521             try:
--> 522                 obj = dict(obj)
    523             except (TypeError, ValueError) as e:

TypeError: 'int' object is not iterable

The above exception was the direct cause of the following exception:

ValidationError                           Traceback (most recent call last)
14 frames
ValidationError: 1 validation error for LineList
__root__
  LineList expected dict not int (type=type_error)

During handling of the above exception, another exception occurred:

OutputParserException                     Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/langchain/output_parsers/pydantic.py](https://localhost:8080/#) in parse_result(self, result, partial)
     27             name = self.pydantic_object.__name__
     28             msg = f"Failed to parse {name} from completion {json_object}. Got: {e}"
---> 29             raise OutputParserException(msg, llm_output=json_object)
     30 
     31     def get_format_instructions(self) -> str:

OutputParserException: Failed to parse LineList from completion 1. Got: 1 validation error for LineList
__root__
  LineList expected dict not int (type=type_error)
```

i'm facing this issue for first time while retrieving the relevant documents. Can you have a look into it?

**Comment by GMartin-dev** [comment] 2024-02-10 02:44
THis is a regression more details here:
https://github.com/langchain-ai/langchain/issues/17352#issuecomment-1936822930

**Comment by baskaryan** [comment] 2024-02-12 22:07
duplicate of duplicate of https://github.com/langchain-ai/langchain/issues/17352

**Closed by baskaryan** 2024-02-12 22:07 UTC
Labels: auto:bug, area: output parsers, integration: openai

**Comment by hafiz031** [comment] 2024-02-18 08:32
`langchain==0.1.5` worked for me.
