### ISSUE TITLE
ValueError: Could not parse LLM output

### ISSUE THREAD

**Issue by eriktlu** [langchain-ai/langchain#1657] opened 2023-03-14 09:01 UTC
I am having trouble using langchain with llama-index (gpt-index). I don't understand what is happening on the langchain side.

When I use OpenAIChat as LLM then sometimes with some user queries I get this error:
```
raise ValueError(f"Could not parse LLM output: `{llm_output}`")
ValueError: Could not parse LLM output: `Thought: Do I need to use a tool? No
```

And to make it worse when I switch to the OpenAI LLM then the agent almost never decides to use the tool. 

I am okay with either solution but I just can't seem to fix it. What is happening?

My code:

```
from langchain.agents import ConversationalAgent, Tool, AgentExecutor
from langchain import OpenAI, LLMChain
from langchain.llms import OpenAIChat

TOOLS = [
    Tool(
        name = "GPT Index",
        func=lambda q: str(INDEX.query(q, llm_predictor=LLM_PREDICTOR, text_qa_template=QA_PROMPT, similarity_top_k=5, response_mode="compact")),
        description="useful for when you need to answer questions about weddings or marriage.",
        return_direct=True
    ),
]

LLM=OpenAIChat(temperature=0)

prefix = """Assistant is a large language model trained by OpenAI.

Assistant is designed to support a wide range of tasks, from answering simple questions to providing detailed explanations and discussions on a wide range of topics. As a language model, Assistant can generate human-like text based on input received, and can provide natural-sounding conversation or consistent, on-topic responses.

Assistant is constantly learning and improving, and its capabilities are always evolving. It can process vast amounts of text to understand and provide accurate and helpful answers to a variety of questions. Additionally, Assistant can generate its own text based on received input, allowing it to participate in discussions on a variety of topics, or provide explanations and commentary.

Overall, Assistant is a powerful tool that can support a variety of tasks and provide valuable insights and information on a wide range of topics. Whether you need help with a specific question or want to have a conversation about a specific topic, Assistant is here to help.

TOOLS:
------
Assistant has access to the following tools."""
suffix = """Answer the questions you know to the best of your knowledge.

Begin!

User Input: {input}
{agent_scratchpad}"""

prompt = ConversationalAgent.create_prompt(
    TOOLS,
    prefix=prefix,
    suffix=suffix,
    input_variables=["input", "agent_scratchpad"]
)

llm_chain = LLMChain(llm=LLM, prompt=prompt)

agent = ConversationalAgent(llm_chain=llm_chain)
agent_executor = AgentExecutor.from_agent_and_tools(agent=agent, tools=TOOLS, verbose=True)

response = agent_executor.run(user_message)
```

**Comment by binbinxue** [comment] 2023-03-14 12:12
I also have this issue, it's worse when i set higher temperature for the model (which tends to make it produce outputs with more variety). These models don't always follow the instructions and that's the issue. I think we need some try catch exception that when LLM don't follow the template then we just return its generated output.

**Comment by itjuba** [comment] 2023-03-15 18:57
Any solution to this ??

**Comment by claust** [comment] 2023-03-15 19:01
This issue is a duplicate of #1477.

**Comment by libratiger** [comment] 2023-03-20 14:23
Same problem,  it is ok to use the `OpenAI`, but not the `ChatOpenAI`

**Comment by eriktlu** [comment] 2023-03-22 05:02
I'm not sure what's the difference or why but I have not had any problems when I use ChatOpenAI from `langchain.chat_models` instead of OpenAIChat.

**Comment by alexprice12** [comment] 2023-03-23 05:39
Hmm, interesting. I think the model (gpt-4) is not obeying the prompt. I'm encountering this issue periodically for all parsers.

**Comment by rishibh7** [comment] 2023-03-30 16:42
Any solution yet? ‘OpenAI’ works fine, but not ‘ChatOpenAI’

**Comment by ninehills** [comment] 2023-04-01 04:05
I solved this question.

When you use  ChatOpenAI model, Please use `chat-conversational-react-description` agent

https://python.langchain.com/en/latest/modules/agents/agents/examples/chat_conversation_agent.html

This agent has been optimized for parsing Chat responses .

**Comment by rishibh7** [comment] 2023-04-01 05:37
> 

I am using dataframe agent, how can i use 'chat-conversational-react-description' agent with it

**Comment by tiagoefreitas** [comment] 2023-09-29 16:21
Can you explain why this is not planned as it seems to be core functionally
to have a proper fix?

**Closed** 2024-01-30 00:52 UTC
