### ISSUE TITLE
[BUG] langchain-openai - max_tokens - 2 confirmed bugs

### ISSUE THREAD

**Issue by ventz** [langchain-ai/langchain#22636] opened 2024-06-06 20:03 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Produces an ERROR with `max_tokens=8192` -- however, the same with a `max_tokens=100` works.

Also, per spec "max_tokens" can be set to `-1`:
```
param max_tokens: int = 256
The maximum number of tokens to generate in the completion. -1 returns as many tokens as possible given the prompt and the models maximal context size.
```

However that produces:

```
Error invoking the chain: Error code: 400 - {'error': {'message': "Invalid 'max_tokens': integer below minimum value. Expected a value >= 1, but got -1 instead.", 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': 'integer_below_min_value'}}
```

Test code:
```python

import dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.output_parsers import StrOutputParser

dotenv.load_dotenv()
llm = ChatOpenAI(
    model="gpt-4",
    temperature=0.2,
    
    # NOTE: setting max_tokens to "100" works. Setting to 8192 or something slightly lower does not. Setting to "-1" fails.
    # Per documentation -1 should work. Also - if "100" calculates the prompt as part of the tokens correctly, so should "8192"
    max_tokens=8192
)

output_parser = StrOutputParser()

prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant. Answer all questions to the best of your ability."),
    MessagesPlaceholder(variable_name="messages"),
])


chain = prompt_template | llm | output_parser

response = chain.invoke({
    "messages": [
        HumanMessage(content="what llm are you"),
    ],
})

print(response)
```

### Error Message and Stack Trace (if applicable)

Error invoking the chain: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, you requested 8225 tokens (33 in the messages, 8192 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### Description

* If it works for "100" max_tokens correctly and it correctly calculates input_prompt as part of it, it should for "8192" or "8100", etc.

* Also - per documentation "-1" should do this calculation automatically, but it fails. 

### System Info

langchain==0.1.20
langchain-aws==0.1.4
langchain-community==0.0.38
langchain-core==0.1.52
langchain-google-vertexai==1.0.3
langchain-openai==0.1.7
langchain-text-splitters==0.0.2

platform mac
Python 3.11.6

**Comment by lucas-tucker** [comment] 2024-06-06 20:47
Hello. I was able to get this to work, although my system info is

langchain==0.2.2
langchain-community==0.0.4
langchain-core==0.2.4
langchain-openai==0.1.8
langchain-text-splitters==0.2.1
langcodes==3.3.0
langsmith==0.1.74

and I was using gpt-4o, which seems to have a 4096 token limit. In particular, I could chain an llm with a token limit of 4096 but not 4097. Setting `max_tokens` to -1 did not work for me, either, though I did not see it in the ChatOpenAI documentation.

**Comment by ventz** [comment] 2024-06-06 20:52
@lucas-tucker Can you test with `gpt-4` -- that's where I am seeing the error.

If possible, also rolling back to langchain to `langchain==0.1.20` (the latest seems to have an issue with Google Vertex unfortunately for Gemini Pro)

What doesn't seem to make sense is why ChatOpenAI does the correct thing with less tokens, but not with higher tokens.

**Comment by ventz** [comment] 2024-06-06 21:30
Setting the max_tokens to "None" seems to calculate the default, but I think this is a bug.

Similar to the way OpenAI implements this correctly, ChatOpenAI should too.
From what I can tell, it seems to cause an issue for GPT-4, but not GPT-4o

**Comment by keenborder786** [comment] 2024-06-06 21:31
@ventz, Can you please point me to the documentation where it says `-1` will work.

**Comment by ventz** [comment] 2024-06-06 21:32
@keenborder786 https://api.python.langchain.com/en/latest/llms/langchain_openai.llms.base.OpenAI.html#langchain_openai.llms.base.OpenAI.max_tokens

**Comment by keenborder786** [comment] 2024-06-06 21:49
Okay, that is for the `OpenAI` Model (LLM) which hits the following [endpoint](https://platform.openai.com/docs/api-reference/completions/create). You can pass `-1` for this model because it uses the following piece of [code](https://github.com/keenborder786/langchain/blob/b6152f26de9f17dfef4f37272aaf70b0d1ced9ff/libs/partners/openai/langchain_openai/llms/base.py#L588) to change `-1` to the number of characters in the prompt.

However, you are using `ChatOpenAI`, which is chat-based and uses messages, hitting the following OpenAI [endpoint](https://platform.openai.com/docs/api-reference/chat). This does not allow passing `-1`, and the langchain documentation does not state anywhere that it does allow this.

Regarding your second issue, the `400` error you face when you pass 8192 tokens is expected. By default, OpenAI reserves 32 tokens for messages titles (titles given in the answer i.e AI,Human etc) while rest for completion (actual answer), and when you set the max tokens to 8192 for the final answer, it seems to exceed the threshold. For GPT-4, choose a max token count to be any figure less than (8192-32), i.e., 8160, and it will work without errors.

I hope this clears your confusion. If it does, please close this issue since it is not a bug with the langchain repo.

PS: Always use `ChatOpenAI` over `OpenAI` because it uses the new endpoint /chat/completions as oppose to `OpenAI` which uses the legacy endpoint /completions

**Comment by keenborder786** [comment] 2024-06-06 21:49
@ventz ^^^

**Comment by efriis** [comment] 2024-06-06 23:36
closing as addressed https://github.com/langchain-ai/langchain/issues/22636#issuecomment-2153461015

**Closed by efriis** 2024-06-06 23:36 UTC
Labels: 🤖:bug, 🔌: openai

**Comment by ventz** [comment] 2024-06-07 02:03
@keenborder786 Understand for the -1

For the second issue (max_tokens of 8192 for ChatOpenAI) -- if I set `8160` with this prompt:

`HumanMessage(content="what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?what llm are you?")

It would error out:
> Error invoking the chain: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, you requested 8373 tokens (213 in the messages, 8160 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

It seems to me that the proper functionality in this case would be to subtract the user prompt ("messages") from the max_tokens, and updating the max_tokens accordingly.

Essentially, max_tokens is being invalidated due to the shared context of the user prompt.

**Comment by ventz** [comment] 2024-06-07 21:03
@efriis Could you please re-open -- the 2nd part seems like a valid bug.

You can replicate it GPT-4, but it does not happen with GPT3.5 Turbo (not some of the larger context models like GPT-4o)

**Comment by ventz** [comment] 2024-06-11 14:33
@efriis Could you please re-open -- the 2nd part seems like a valid bug.

It seems the max_tokens is not accounting for the prompt.

**Comment by ventz** [comment] 2024-06-11 14:51
I am opening a new dedicated issue for the 2nd issue as it does seem to be a bug:

https://github.com/langchain-ai/langchain/issues/22778

max_tokens is not correctly accounting for the prompt, and it happens to work in a low example (ex: 100) because it's overflowing into the remaining context window.
