### ISSUE TITLE
ChromaDb EmbeddingFunction definition updated

### ISSUE THREAD

**Issue by jayant-yadav** [langchain-ai/langchain#13061] opened 2023-11-08 14:11 UTC
### System Info

Using Google Colab Free version with T4 GPU. 
chromadb==0.4.16

### Who can help?

@agola11 @hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

As per the latest Chromadb migration logs ([link](https://docs.trychroma.com/migration#migration-to-0416---november-7-2023)) `EmbeddingFunction` defnition has been updated and it affects all the custom made embedding function.   
What this means is the `langchain.embeddings.HuggingFaceBgeEmbeddings` is inconsistent with this new definition and throws the following error:  
```py
ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023 
```
The above code can be reproduced by inserting documents into Chromadb embedded using `HuggingFaceBgeEmbeddings` like so:  
```py  
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.embeddings import HuggingFaceBgeEmbeddings
from transformers import AutoTokenizer

embedding_function = HuggingFaceBgeEmbeddings(
    model_name="BAAI/bge-base-en-v1.5",
    model_kwargs={'device': 'cuda'},
    encode_kwargs={'normalize_embeddings': True},
    query_instruction="Represent this sentence for searching relevant passages: "
)  
tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-base-en-v1.5')
text_splitter = RecursiveCharacterTextSplitter.from_huggingface_tokenizer(
    tokenizer, chunk_size=100, chunk_overlap=0
)
text = 'Some text that needs to be embedded.'
print(len(embedding_function.embed_query(text))) # works so far
splits = text_splitter.create_documents([text])
db = Chroma.from_documents(splits, embedding_function, persist_directory="./chroma_db")
```

I am not sure, but the answer might lie in correcting the `HuggingFaceBgeEmbeddings` class : [link](https://github.com/langchain-ai/langchain/blob/1f27104626fc71a5199df965011810426dd2eede/libs/langchain/langchain/embeddings/huggingface.py#L188) ?

### Expected behavior

The expected behaviour would have made a valid `db` object upon running the code  
```py 
db = Chroma.from_documents(splits, embedding_function, persist_directory="./chroma_db")

**Comment by mattalford** [comment] 2023-11-08 16:00
Quick work around until the HuggingFaceEmbeddings is updated.
`pip install chromadb==0.4.15`

This breaking change affects chromadb 0.4.16

**Comment by efriis** [comment] 2023-11-08 21:39
Langchain 0.0.332 released with the chroma team's fix for compatibility with chromadb>=0.4.16

Can now use latest of both `pip install -U langchain chromadb`

**Closed by efriis** 2023-11-08 21:39 UTC
Labels: area: embeddings, area: vector store, auto:bug, integration: chroma

**Comment by efriis** [comment] 2023-11-08 21:40
Actually looks like there was something specific with `HuggingFaceBgeEmbeddings` as well - could you confirm 0.0.332 with the chroma fix addresses this, and reopen if it's something that needs to be addressed in hugging face?

**Comment by jayant-yadav** [comment] 2023-11-08 22:31
@efriis The fix in 0.0.332 works! Now langchain's latest version (0.0.332) is compatible with chromadb==0.4.16.

**Comment by efriis** [comment] 2023-11-09 18:33
#13085

**Comment by BharatBindage** [comment] 2023-11-28 13:55
> Actually looks like there was something specific with `HuggingFaceBgeEmbeddings` as well - could you confirm 0.0.332 with the chroma fix addresses this, and reopen if it's something that needs to be addressed in hugging face?

This is fixed now .. Thank you efriis

**Comment by xsuryanshx** [comment] 2023-12-10 12:44
> Langchain 0.0.332 released with the chroma team's fix for compatibility with chromadb>=0.4.16
> 
> Can now use latest of both `pip install -U langchain chromadb`

thanks this fixed my error!

**Comment by jashshah** [comment] 2024-05-24 14:14
I am using chromadb-0.5.0 and langchain-0.2.1 and I still run into this error when I try to host ChromaDB using a docker container. 

```

hf = HuggingFaceBgeEmbeddings(
    model_name=modelPath,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs, 
    cache_folder="./cache"
)

chroma_client = chromadb.HttpClient(host='localhost', port=8000)

collection = chroma_client.create_collection(name="DATA_V3",embedding_function=hf)

```

**Comment by lcotonea** [comment] 2024-08-02 08:29
I reproduced the same problem than @jashshah with : 

- Chromadb server part : v0.5.5 dockerized (arm64)
- Client part : langchain 0.2.11, langchain_community 0.2.10, langchain-huggingface 0.0.3

**Comment by efriis** [comment] 2024-08-02 17:38
Hey! Could you try with the `langchain-chroma` package instead? https://python.langchain.com/v0.2/docs/integrations/vectorstores/chroma/#basic-example
