### ISSUE TITLE
Issue: OpenAI Bad Gateway results in Error in on_retry: asyncio.run() cannot be called from a running event loop (coroutine 'AsyncRunManager.on_retry' was never awaited) inside openai.acompletion_with_retry

### ISSUE THREAD

**Issue by maspotts** [langchain-ai/langchain#8462] opened 2023-07-29 17:11 UTC
### Issue you'd like to raise.

I just saw a novel error, which appears to be triggered by a failed OpenAI API call (inside an asynchronous block) which is causing an asyncio.run() inside an asyncio.run().  Error pasted below.  Is this my (user) error?  Or possibly a problem with the acompletion_with_retry() implementation?

```
2023-07-29 05:53:14,838 INFO     message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=None response_code=502
2023-07-29 05:53:14,838 INFO     error_code=502 error_message='Bad gateway.' error_param=None error_type=cf_bad_gateway message='OpenAI API error received' stream_error=False
2023-07-29 05:53:14,839 WARNING  Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Bad gateway. {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}} 502 {'error': {'code': 502, 'message': 'Bad gateway.', 'param': None, 'type': 'cf_bad_gateway'}} <CIMultiDictProxy('Date': 'Sat, 29 Jul 2023 05:53:14 GMT', 'Content-Type': 'application/json', 'Content-Length': '84', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '7ee3120dab9f1084-ORD', 'alt-svc': 'h3=":443"; ma=86400')>.
2023-07-29 05:53:14,839 ERROR    Error in on_retry: asyncio.run() cannot be called from a running event loop
/usr/local/python-modules/tenacity/__init__.py:338: RuntimeWarning: coroutine 'AsyncRunManager.on_retry' was never awaited
  self.before_sleep(retry_state)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by walkward** [comment] 2023-08-02 22:49
I'm observing a big spike from this as well.

@hinthornw Looks like this error was likely introduced in https://github.com/langchain-ai/langchain/pull/8053. Any ideas?

**Comment by ryanstout** [comment] 2023-08-05 18:31
@maspotts I'm seeing similar, what type of code are you running that is causing this? Thanks

**Comment by kylrth** [comment] 2023-08-06 19:19
The problem is that [`create_base_retry_decorator`](https://github.com/langchain-ai/langchain/blob/15c271e7b3cc658f56c9e9ffcebe4c1bb51dc60c/libs/langchain/langchain/llms/base.py#L77) tries to `asyncio.run` something in the `before_sleep` callback, which breaks things when this is all happening inside an `agenerate` call.

**Comment by ryanstout** [comment] 2023-08-06 22:45
@kylrth Thanks for the info, yea, I think I'm seeing similar. What kind of code are you running that causes it. For me it's doing a MapReduce.

**Comment by kylrth** [comment] 2023-08-08 14:42
I see it with just `ChatOpenAI.agenerate` when OpenAI returns a 502.

**Comment by ShantanuNair** [comment] 2023-09-07 11:53
@hwchase17 Any chance someone's looking at this? It's a source of high billables potentially.

**Comment by ShantanuNair** [comment] 2023-09-13 09:58
@maspotts I'm looking into this too, do you see the same issue on the latest version? @kylrth can you expand a bit more on why the asyncio.run is problematic here? I am running into this issue with agenerate, and notice my retries don't run after 4/8/10 seconds as they should - they are run after about 6-7 minutes, and I'm wondering if fixing this bug may fix my issue of retries from 502s failing.  Maybe I can take a go at tackling this.

**Comment by ShantanuNair** [comment] 2023-09-13 13:32
> @kylrth Thanks for the info, yea, I think I'm seeing similar. What kind of code are you running that causes it. For me it's doing a MapReduce.

Me too. A mapreduce chain via analayzeDocumentsChain

**Comment by kylrth** [comment] 2023-09-13 13:34
I think this issue is closed by #8659. @hinthornw ?

**Comment by ShantanuNair** [comment] 2023-09-13 14:22
@kylrth Hah, I was just running through the same PR. Looks like the way tenacity's retry decorator works takes care of the async/sync switch. Can I ask - can you verify that on recent langchain that retries do indeed work after X (2/4/8) seconds? For me it's hanging for 6-7 minutes between retries even though it prints our retrying in X time.

**Comment by ShantanuNair** [comment] 2023-09-20 08:43
So important notes regarding this issue from my investigation:

1) If using Async calls, when you receive a 502 bad gateway, it will timeout after the whole 600s. https://github.com/openai/openai-python/pull/387 Needs to be fixed in openai-python. We need read timeouts and not a total timeout.
2) After stalling your chain for the entirety of 10 minutes, you WILL BE BILLED for no generation, besides it absolutely destroying experience by forcing one part of the chain to wait an entire 10 minutes.

**Comment by nfcampos** [comment] 2023-09-25 09:43
@hinthornw this was fixed in https://github.com/langchain-ai/langchain/pull/8659 right? If so, lets close it

**Closed** 2023-09-25 09:44 UTC
Labels: auto:bug
