### ISSUE TITLE
convert_to_openai_function will drop `title` field in `output_schema` if it's a Pydantic model.

### ISSUE THREAD

**Issue by elonzh** [langchain-ai/langchain#18319] opened 2024-02-29 11:45 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from pprint import pprint
from langchain_core.utils.function_calling import convert_to_openai_function
from pydantic import v1

class BiblioExtraction(v1.BaseModel):
    title: str
    authors: list[str]

f = convert_to_openai_function(BiblioExtraction)
pprint(f)
```

### Error Message and Stack Trace (if applicable)

```python
{'description': '',
 'name': 'BiblioExtraction',
 'parameters': {'properties': {'authors': {'items': {'type': 'string'},
                                           'type': 'array'}},
                'required': ['title', 'authors'],
                'type': 'object'}}
```

### Description

I am trying to use `langchain.chains.openai_functions.create_structured_output_runnable` to extract citation information from the text, and then I found that I cannot extract the `title` field. 

After investigation, I discovered that langchain [introduced an undocumented behavior](https://github.com/langchain-ai/langchain/commit/ef42d9d559bf8e9c7de85f20fe9a67cc78c3030a#diff-5244d0e3a3878e2e86fbdac70ff585a1f956939c46ef65e53c77fd896bc03bd6R53) in version 0.1.4, which deletes the `title` field in schema.

### System Info

```
❯ python -m langchain_core.sys_info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Thu Oct 5 21:02:42 UTC 2023
> Python Version:  3.10.13 (main, Nov 16 2023, 15:58:41) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.27
> langchain: 0.1.9
> langchain_community: 0.0.24
> langsmith: 0.1.5
> langchain_openai: 0.0.5

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

```

**Comment by keenborder786** [comment] 2024-03-03 13:39
The unexpected behaviour is caused by [rm_titles](https://github.com/keenborder786/langchain/blob/18c7e827281a8aee29de4429fb5b4db3e88bfc27/libs/core/langchain_core/utils/function_calling.py#L76) being set to True by default. Also, if you urgently want to use the tool then why don't you change the spelling of your parameter e.g title to title_extracted since that will also fix your isse.

**Comment by keenborder786** [comment] 2024-03-03 13:41
@elonzh Actually I am closing the PR because that bring in unexpected breaking changes in other parts of code. I would recommend you to use alternative name for tile e.g `tile_extracted`. That will serve your purpose.

**Comment by Gregory-Gerard** [comment] 2024-03-28 13:00
Same here. The pain is that it's not documented, and can be time-consuming to find the actual problem. For the moment I've renamed my `title`, but it would be nice to be able to modify this behavior via an argument, for example.

**Closed** 2024-07-04 16:07 UTC
Labels: 🤖:bug, 🔌: openai, Ɑ:  Runnables
