### ISSUE TITLE
Issue: update prompts for local LLM

### ISSUE THREAD

**Issue by yiouyou** [langchain-ai/langchain#15008] opened 2023-12-21 12:27 UTC
### Issue you'd like to raise.

To fit the prompt from openai to some other local LLM, what's the best way to update the prompts in langchain.chains.query_constructor.prompt while keeping the rest code the same?

**Comment by yiouyou** [comment] 2023-12-21 12:54
Could you give an example about how to update prompts in langchain.chains.query_constructor.prompt? It's not about what kind of format of prompt I cound write. Do I need to change the text in source code, or update some class with custome code?

**Comment by deepak-habilelabs** [comment] 2023-12-21 16:05
@yiouyou can u pls help me figuring out error in my custom prompt template
below is my code
def generate_custom_prompt(query):   
    # Create the custom prompt template
    custom_prompt_template = f"""You are a chatbot designed to provide helpful answers to user questions. If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
    User's Question: {query}    
    In your response, aim for clarity and conciseness. Provide information that directly addresses the user's query. If the answer requires additional details, feel free to ask clarifying questions.
    Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

    Your Helpful Answer:"""

    # Create the PromptTemplate
    custom_prompt = PromptTemplate(
        template=custom_prompt_template, input_variables=["query"]
    )

    # Format the prompt
    formatted_prompt = custom_prompt.format(query=query)

    return formatted_prompt
    
    and below is the error i am getting
      File "/home/hs/CustomBot/accounts/common_langcain_qa.py", line 40, in generate_custom_prompt
    formatted_prompt = custom_prompt.format(query=query)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/prompt.py", line 132, in format
    return DEFAULT_FORMATTER_MAPPING[self.template_format](self.template, **kwargs)
  File "/usr/lib/python3.8/string.py", line 163, in format
    return self.vformat(format_string, args, kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/utils/formatting.py", line 29, in vformat
    return super().vformat(format_string, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 168, in vformat
    self.check_unused_args(used_args, args, kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/utils/formatting.py", line 18, in check_unused_args
    raise KeyError(extra)
KeyError: {'query'}

**Comment by Yanni8** [comment] 2023-12-21 20:33
> @yiouyou can u pls help me figuring out error in my custom prompt template

Well the problem is that you don't define a query `prompt variable`. 
This should work

```python
# Create the PromptTemplate
custom_prompt = PromptTemplate(
    template=custom_prompt_template, input_variables=["input"]
)

# Format the prompt
formatted_prompt = custom_prompt.format(input=input)

return formatted_prompt
```

**Comment by deepak-habilelabs** [comment] 2023-12-22 08:30
> > @yiouyou can u pls help me figuring out error in my custom prompt template
> 
> Well the problem is that you don't define a query `prompt variable`. This should work
> 
> ```python
> # Create the PromptTemplate
> custom_prompt = PromptTemplate(
>     template=custom_prompt_template, input_variables=["input"]
> )
> 
> # Format the prompt
> formatted_prompt = custom_prompt.format(input=input)
> 
> return formatted_prompt
> ```

no i defined but, the format of input of formatted_prompt variable is formatted_prompt = custom_prompt.format()
i resolved by applying this.

**Comment by cyai** [comment] 2023-12-24 17:20
@deepak-habilelabs I could see that you've used f-string for `custom_prompt_template` in your code.
Instead you could just use it as string.

Here,

```python
def generate_custom_prompt(query):
# Create the custom prompt template
custom_prompt_template = """You are a chatbot designed to provide helpful answers to user questions. If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
User's Question: {query}
In your response, aim for clarity and conciseness. Provide information that directly addresses the user's query. If the answer requires additional details, feel free to ask clarifying questions.
Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

Your Helpful Answer:"""

# Create the PromptTemplate
custom_prompt = PromptTemplate(
    template=custom_prompt_template, input_variables=["query"]
)

# Format the prompt
formatted_prompt = custom_prompt.format(query=query)

return formatted_prompt
```

**Comment by deepak-habilelabs** [comment] 2024-01-11 13:22
> @deepak-habilelabs I could see that you've used f-string for `custom_prompt_template` in your code. Instead you could just use it as string.
> 
> Here,
> 
> ```python
> def generate_custom_prompt(query):
> # Create the custom prompt template
> custom_prompt_template = """You are a chatbot designed to provide helpful answers to user questions. If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
> User's Question: {query}
> In your response, aim for clarity and conciseness. Provide information that directly addresses the user's query. If the answer requires additional details, feel free to ask clarifying questions.
> Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.
> 
> Your Helpful Answer:"""
> 
> # Create the PromptTemplate
> custom_prompt = PromptTemplate(
>     template=custom_prompt_template, input_variables=["query"]
> )
> 
> # Format the prompt
> formatted_prompt = custom_prompt.format(query=query)
> 
> return formatted_prompt
> ```

@cyai thank you for your response, it's been already solved 
did you implemented memory with conversational retreival chain?

**Comment by cyai** [comment] 2024-01-16 08:40
Hi @deepak-habilelabs,
yes, you can implement memory with conversational retreival chain. You need to pass the `memory` parameter while creating the chain object.

you need to get the `memory` from the `ConversationBufferMemory`.

Like this:
```python
memory = ConversationBufferMemory(memory_key='chat_history', return_messages=False)
conv_qa_chain = ConversationalRetrievalChain.from_llm(
    llm=llm, 
    retriever=retriever, 
    memory=memory,
    get_chat_history=lambda h : h)
```

Refer the official document [here](https://api.python.langchain.com/en/latest/chains/langchain.chains.conversational_retrieval.base.ConversationalRetrievalChain.html)

**Closed** 2024-04-23 17:06 UTC
Labels: 🤖:question, Ɑ:  models
