### ISSUE TITLE
Cassandra Exact Cache issue: TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by debasishdas033** [langchain-ai/langchain#23896] opened 2024-07-05 05:15 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from cassandra.cluster import Cluster
from ssl import PROTOCOL_TLSv1_2, SSLContext, CERT_NONE, PROTOCOL_TLS, PROTOCOL_SSLv23
from cassandra.auth import PlainTextAuthProvider
from asyncio.log import logger
from config import *

from langchain_openai import AzureChatOpenAI
from langchain.globals import set_llm_cache
from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn
from langchain.schema import HumanMessage
from langchain_core.messages import AIMessage
from langchain_core.outputs.chat_generation import ChatGeneration
from langchain_core.load import dumps
import cassio
from langchain_community.cache import CassandraCache
#creating generation_info for ChatGeneration Object from 'res' <AIMessage Object>

#creating ChatGeneration Object
cluster = Cluster(['*******************'], port = 9042)
session = cluster.connect()
print(session)

aoai_endpoint = '******************************************************'
aoai_api_key = '****************************************************'
aoai_api_version = '2024-05-01-preview'
app = FastAPI()

class Item(BaseModel):
    question: str

llm = AzureChatOpenAI(
        model='gpt-4o',
        azure_endpoint=aoai_endpoint,
        azure_deployment='gpt-4o',
        api_version=aoai_api_version,
        api_key=aoai_api_key,
        temperature=0.0,
        max_tokens=4000,
        )
@app.post("/askquestion")
def say_joke(item: Item):
    cassio.init(session=session, keyspace='cycling')
    set_llm_cache(CassandraCache())
    message = HumanMessage(content=item.question)
    response = llm.invoke([message])

    return response.content

if __name__ == "__main__":
    uvicorn.run(host="0.0.0.0", port=8000, app=app)

### Error Message and Stack Trace (if applicable)

INFO:     172.26.64.1:52437 - "POST /askquestion HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/Langchain/test.py", line 47, in say_joke
    response = llm.invoke([message])
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 248, in invoke
    self.generate_prompt(
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 681, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 538, in generate
    raise e
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 528, in generate
    self._generate_with_cache(
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 712, in _generate_with_cache
    llm_string = self._get_llm_string(stop=stop, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 455, in _get_llm_string
    _cleanup_llm_representation(serialized_repr, 1)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 1239, in _cleanup_llm_representation
    _cleanup_llm_representation(value, depth + 1)
  File "/home/dd/LLAMA/llmvenv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 1229, in _cleanup_llm_representation
    if serialized["type"] == "not_implemented" and "repr" in serialized:
       ~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'

### Description

We are trying to implement Cassandra Exact Caching with our example code. We have used Azure Managed Cassandra instance and standalone docker instance as well. 
But the code did not work with either of these DB setup.

With a simple tweaking in the Lang chain source code (python3.12/site-packages/langchain_core/language_models/chat_models.py).
Line# 455(_cleanup_llm_representation(serialized_repr, 1)) in the above python code was commented and after that it worked.
====================================================================

def _get_llm_string(self, stop: Optional[List[str]] = None, **kwargs: Any) -> str:
        if self.is_lc_serializable():
            params = {**kwargs, **{"stop": stop}}
            param_string = str(sorted([(k, v) for k, v in params.items()]))
            # This code is not super efficient as it goes back and forth between
            # json and dict.
            serialized_repr = dumpd(self)
            **_cleanup_llm_representation(serialized_repr, 1)**
            llm_string = json.dumps(serialized_repr, sort_keys=True)
            return llm_string + "---" + param_string
        else:
            params = self._get_invocation_params(stop=stop, **kwargs)
            params = {**params, **kwargs}
            return str(sorted([(k, v) for k, v in params.items()]))

### System Info

(llmvenv) dd@KDC1-L-3326K00:~/Langchain$ pip show langchain-community
Name: langchain-community
Version: 0.2.6
Summary: Community contributed LangChain integrations.
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /home/dd/LLAMA/llmvenv/lib/python3.12/site-packages
Requires: aiohttp, dataclasses-json, langchain, langchain-core, langsmith, numpy, PyYAML, requests, SQLAlchemy, tenacity
Required-by:
(llmvenv) dd@KDC1-L-3326K00:~/Langchain$
============================================================
(llmvenv) dd@KDC1-L-3326K00:~/Langchain$ pip show cassandra-driver
Name: cassandra-driver
Version: 3.29.1
Summary: DataStax Driver for Apache Cassandra
Home-page: http://github.com/datastax/python-driver
Author: DataStax
Author-email:
License:
Location: /home/dd/LLAMA/llmvenv/lib/python3.12/site-packages
Requires: geomet
Required-by: cassio
(llmvenv) dd@KDC1-L-3326K00:~/Langchain$
=============================================================
(llmvenv) dd@KDC1-L-3326K00:~/Langchain$ pip show cassio
Name: cassio
Version: 0.1.8
Summary: A framework-agnostic Python library to seamlessly integrate Apache Cassandra(R) with ML/LLM/genAI workloads.
Home-page: https://cassio.org
Author: Stefano Lottini
Author-email: stefano.lottini@datastax.com
License: Apache-2.0
Location: /home/dd/LLAMA/llmvenv/lib/python3.12/site-packages
Requires: cassandra-driver, numpy, requests
Required-by:
(llmvenv) dd@KDC1-L-3326K00:~/Langchain$

**Comment by radiachkik** [comment] 2024-07-05 07:22
I am experiencing the same. The code that used to work a couple of days ago now throws the same error. We are not using Cassandra or anything. Simply runing the ChatAnthropic model.

**Comment by reaperkrew** [comment] 2024-07-05 12:26
Hey all, I think it might be related to [this issue](https://github.com/langchain-ai/langchain/issues/23824). It looks like a fix has been merged, just waiting on a release now.

Seems to be related to `set_llm_cache()`. Cassandra and SQLLite caches have been affected for me, I saw others reporting RedisCache was also affected.

**Comment by ntvuongg** [comment] 2024-07-05 16:44
Try this:
```
pip install langchain-core==0.2.9
```
Worked for me

**Comment by debasishdas033** [comment] 2024-07-05 17:50
> Try this:
> 
> ```
> pip install langchain-core==0.2.9
> ```
> 
> Worked for me

0.2.9 has compatibility issue with langchain-community 0.2.6. So I installed langchain-core==0.2.10. It resolved the issue.

**Comment by eyurtsev** [comment] 2024-07-05 19:05
Closing as this is a duplicate of: https://github.com/langchain-ai/langchain/issues/23824

**Closed by eyurtsev** 2024-07-05 19:05 UTC
Labels: 🤖:bug
