### ISSUE TITLE
When using a Pydantic model as input to a @chain-decorated function, `input_schema.schema()` gives an error 

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langchain#16623] opened 2024-01-26 10:22 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python

from langchain_core.runnables import chain
from pydantic import BaseModel

class MyConversation(BaseModel):
    messages: list

    
@chain
def conversation_to_history( conversation: MyConversation) -> str:
    return "hi :)"


print(conversation_to_history.input_schema.schema())
```

### Error Message and Stack Trace (if applicable)

```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[6], [line 25](vscode-notebook-cell:?execution_count=6&line=25)
     [20](vscode-notebook-cell:?execution_count=6&line=20)             history.add_user_message(message.body)
     [22](vscode-notebook-cell:?execution_count=6&line=22)     return history
---> [25](vscode-notebook-cell:?execution_count=6&line=25) conversation_to_history.input_schema.schema()

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:664](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:664), in BaseModel.schema(cls, by_alias, ref_template)
    [662](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:662) if cached is not None:
    [663](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:663)     return cached
--> [664](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:664) s = model_schema(cls, by_alias=by_alias, ref_template=ref_template)
    [665](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:665) cls.__schema_cache__[(by_alias, ref_template)] = s
    [666](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/main.py:666) return s

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:188](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:188), in model_schema(model, by_alias, ref_prefix, ref_template)
    [186](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:186) model_name_map = get_model_name_map(flat_models)
    [187](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:187) model_name = model_name_map[model]
--> [188](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:188) m_schema, m_definitions, nested_models = model_process_schema(
    [189](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:189)     model, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix, ref_template=ref_template
    [190](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:190) )
    [191](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:191) if model_name in nested_models:
    [192](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:192)     # model_name is in Nested models, it has circular references
    [193](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:193)     m_definitions[model_name] = m_schema

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:582](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:582), in model_process_schema(model, by_alias, model_name_map, ref_prefix, ref_template, known_models, field)
    [580](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:580)     s['description'] = doc
    [581](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:581) known_models.add(model)
--> [582](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:582) m_schema, m_definitions, nested_models = model_type_schema(
    [583](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:583)     model,
    [584](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:584)     by_alias=by_alias,
    [585](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:585)     model_name_map=model_name_map,
    [586](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:586)     ref_prefix=ref_prefix,
    [587](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:587)     ref_template=ref_template,
    [588](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:588)     known_models=known_models,
    [589](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:589) )
    [590](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:590) s.update(m_schema)
    [591](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:591) schema_extra = model.__config__.schema_extra

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:623](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:623), in model_type_schema(model, by_alias, model_name_map, ref_template, ref_prefix, known_models)
    [621](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:621) for k, f in model.__fields__.items():
    [622](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:622)     try:
--> [623](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:623)         f_schema, f_definitions, f_nested_models = field_schema(
    [624](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:624)             f,
    [625](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:625)             by_alias=by_alias,
    [626](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:626)             model_name_map=model_name_map,
    [627](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:627)             ref_prefix=ref_prefix,
    [628](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:628)             ref_template=ref_template,
    [629](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:629)             known_models=known_models,
    [630](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:630)         )
    [631](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:631)     except SkipField as skip:
    [632](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:632)         warnings.warn(skip.message, UserWarning)

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:256](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:256), in field_schema(field, by_alias, model_name_map, ref_prefix, ref_template, known_models)
    [253](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:253)     s.update(validation_schema)
    [254](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:254)     schema_overrides = True
--> [256](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:256) f_schema, f_definitions, f_nested_models = field_type_schema(
    [257](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:257)     field,
    [258](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:258)     by_alias=by_alias,
    [259](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:259)     model_name_map=model_name_map,
    [260](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:260)     schema_overrides=schema_overrides,
    [261](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:261)     ref_prefix=ref_prefix,
    [262](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:262)     ref_template=ref_template,
    [263](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:263)     known_models=known_models or set(),
    [264](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:264) )
    [266](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:266) # $ref will only be returned when there are no schema_overrides
    [267](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:267) if '$ref' in f_schema:

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:528](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:528), in field_type_schema(field, by_alias, model_name_map, ref_template, schema_overrides, ref_prefix, known_models)
    [526](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:526) else:
    [527](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:527)     assert field.shape in {SHAPE_SINGLETON, SHAPE_GENERIC}, field.shape
--> [528](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:528)     f_schema, f_definitions, f_nested_models = field_singleton_schema(
    [529](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:529)         field,
    [530](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:530)         by_alias=by_alias,
    [531](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:531)         model_name_map=model_name_map,
    [532](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:532)         schema_overrides=schema_overrides,
    [533](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:533)         ref_prefix=ref_prefix,
    [534](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:534)         ref_template=ref_template,
    [535](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:535)         known_models=known_models,
    [536](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:536)     )
    [537](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:537)     definitions.update(f_definitions)
    [538](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:538)     nested_models.update(f_nested_models)

File [~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:952](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:952), in field_singleton_schema(field, by_alias, model_name_map, ref_template, schema_overrides, ref_prefix, known_models)
    [949](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:949) if args is not None and not args and Generic in field_type.__bases__:
    [950](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:950)     return f_schema, definitions, nested_models
--> [952](https://file+.vscode-resource.vscode-cdn.nethiddenpath~/.venvs/langchain_tests_venv/lib/python3.11/site-packages/pydantic/v1/schema.py:952) raise ValueError(f'Value not declarable with JSON Schema, field: {field}')

ValueError: Value not declarable with JSON Schema, field: name='__root__' type=Optional[MyConversation] required=False default=None


```

### Description

I expected to be able to pass an object annotated with a Pydantic model (Pydantic is used elsewhere in langchain for annotating input/output types), but when I try to get the input schema for the resulting chain, I get the above error.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Fri, 05 Jan 2024 15:35:19 +0000
> Python Version:  3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]

Package Information
-------------------
> langchain_core: 0.1.16
> langchain: 0.1.4
> langchain_community: 0.0.16
> langchain_openai: 0.0.2.post1
> langgraph: 0.0.12

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by ccurme** [comment] 2024-01-26 15:39
Not sure if this is a good solution but I can reproduce this problem and resolve it by changing `from pydantic import BaseModel` to `from pydantic.v1 import BaseModel` (or `from langchain_core.pydantic_v1 import BaseModel`).

**Comment by eyurtsev** [comment] 2024-01-26 17:37
@idcore Please see pydantic guidelines when working with langchain. LangChain has to support both pydantic 1 and 2 since both versions are about equally downloaded right now. When using pydantic 2 you need to use the v1 namespace within it.

**Comment by eyurtsev** [comment] 2024-01-26 17:38
Closing since we do not expect this to work until we fully transition to pydantic 2

**Closed by eyurtsev** 2024-01-26 17:38 UTC
Labels: pydantic
