### ISSUE TITLE
Cannot set up dev container because of Poetry solving dependencies forever

### ISSUE THREAD

**Issue by juliensalinas** [langchain-ai/langchain#7825] opened 2023-07-17 08:08 UTC
### System Info

OS: Ubuntu 22.04
Docker version: Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
VSCode: 1.69.0

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Go to this documentation page: https://github.com/hwchase17/langchain/tree/master/.devcontainer
2. Click the "Dev Containers Open" button
3. The dev image build is stuck at the last step (Poetry dependencies installation).

When making the Poetry more verbose, it appears that it loops forever on dependencies, like this:

```
   8: derived: pytz-deprecation-shim
   8: fact: pytz-deprecation-shim (0.1.0.post0) depends on tzdata (*)
   8: fact: pytz-deprecation-shim (0.1.0.post0) depends on backports.zoneinfo (*)
   8: selecting pytz-deprecation-shim (0.1.0.post0)
   8: fact: tensorflow-hub (0.14.0) depends on numpy (>=1.12.0)
   8: fact: tensorflow-hub (0.14.0) depends on protobuf (>=3.19.6)
   8: selecting tensorflow-hub (0.14.0)
   8: selecting termcolor (2.3.0)
   8: fact: watchfiles (0.19.0) depends on anyio (>=3.0.0)
   8: selecting watchfiles (0.19.0)
   8: selecting pathspec (0.11.1)
   8: fact: grpcio-reflection (1.47.5) depends on protobuf (>=3.12.0)
   8: fact: grpcio-reflection (1.47.5) depends on grpcio (>=1.47.5)
   8: selecting grpcio-reflection (1.47.5)
   8: selecting iniconfig (2.0.0)
   8: fact: pycares (4.3.0) depends on cffi (>=1.5.0)
   8: selecting pycares (4.3.0)
   8: derived: cffi (>=1.5.0)
   8: selecting colored (1.4.4)
   8: fact: azure-core (1.28.0) depends on requests (>=2.18.4)
   8: fact: azure-core (1.28.0) depends on six (>=1.11.0)
   8: fact: azure-core (1.28.0) depends on typing-extensions (>=4.3.0)
 ```

I even tried to wait for 5 hours, but it was not enough (my internet connection works correctly).

### Expected behavior

The dev container environment should be up and ready in a couple of minutes.

**Comment by batmanscode** [comment] 2023-07-17 11:22
It's a little old, but maybe you can try giving the devcontainer in #1159 a try

**Comment by juliensalinas** [comment] 2023-07-18 08:48
Thanks @batmanscode 

After testing the .devcontainer with VSCode, I just tested it with Github Codespaces. Same problem, it is hanging forever:

![Screenshot from 2023-07-18 10-44-38](https://github.com/hwchase17/langchain/assets/22055188/e02eef17-2129-4917-98ad-4ff681eed93f)

I also try changing the Poetry version from 1.3.2 to 1.5.1 in https://github.com/hwchase17/langchain/blob/master/dev.Dockerfile , but same problem.

**Comment by juliensalinas** [comment] 2023-07-18 09:25
Thank you @batmanscode , I appreciate it!

**Comment by jasonsimmons** [comment] 2023-08-01 18:48
Struggling with this as well.

**Comment by amovfx** [comment] 2023-08-09 18:52
Also having problems here, I tried some remedies in @alecf 's post above to no avail. M1 Mac.

**Comment by zackproser** [comment] 2023-08-15 02:28
Noticing this myself both locally via vscode and in GitHub codespaces - resolving dependencies hangs forever.

**Comment by balnarendrasapa** [comment] 2023-09-02 19:28
I just had this idea. Is it possible to use an image for devcontainer that is already built. I mean if it was already built, only overhead is downloading it right? I noticed that image is being built using the docker-compose file. So maybe can build the image for one time and publish it to the github packages or docker hub and reference that in this docker-compose file. Does this approach work?

What do you guys think?

**Comment by slangenbach** [comment] 2023-10-27 20:11
After taking a closer look at _devcontainer.json_, _docker-compose.yaml_ and _libs/langchain/dev.Dockerfile_, I wonder about the complexity.  

Couldn't this be simplified to a standard devcontainer config including:
- **image**: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye (same distro as well as Python major and minor version as used in _libs/langchain/DockerFile_ for running unit tests) 
- **features**: poetry 1.4.2 (same version as used in Dockerfile for running unit tests)
- **postCreateCommand**: setup.sh

With setup.sh containing:
```bash
#!/bin/bash
poetry completions bash >> ~/.bash_completion
cd libs/langchain
# Installs main, test, codespell, lint, typing (all non-optional) and dev dependencies
poetry install --no-interaction --no-ansi --with dev
```

Creating a devcontainer with the config above only took a few minutes on my M2 mac.
Happy to contribute a PR to fix this.

**Comment by observeinc-infra** [comment] 2023-11-20 21:14
The problem is not "poetry is slow in containers," the problem is "poetry does an exhaustive enumeration of dependencies, leading to combinatoric explosion, in lieu of an efficient constraint solver algorithm."

FWIW:
```
 => [langchain-dev-dependencies 3/3] RUN poetry install -vv --no-interaction --no-ansi --with dev,test                          9317.7s
```
Yup, that's three hours to build the container, on a 8-core AWS instance with great networking.

**Comment by ZyeG** [comment] 2023-11-29 02:52
same issue. stuck at poetry solving dependencies for a long time, then exit code1, container server terminated (code:137, signal:null). I am using the command from .devcontainer>readme `https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/<yourusername>/<yourclonedreponame>`. Anyone has same issue? any suggestions appreciated

**Closed** 2024-03-13 19:56 UTC
Labels: 🤖:bug
