### ISSUE TITLE
ImportError: cannot import name 'string_types' from 'sqlalchemy.util.compat'

### ISSUE THREAD

**Issue by Abe410** [langchain-ai/langchain#17616] opened 2024-02-16 04:17 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain_community.utilities import SQLDatabase
db = SQLDatabase.from_uri(URI)
```

### Error Message and Stack Trace (if applicable)

```
{
	"name": "ImportError",
	"message": "cannot import name 'string_types' from 'sqlalchemy.util.compat' (/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 db = SQLDatabase.from_uri(URI)

File ~/.local/lib/python3.10/site-packages/langchain_community/utilities/sql_database.py:133, in SQLDatabase.from_uri(cls, database_uri, engine_args, **kwargs)
    131 \"\"\"Construct a SQLAlchemy engine from URI.\"\"\"
    132 _engine_args = engine_args or {}
--> 133 return cls(create_engine(database_uri, **_engine_args), **kwargs)

File <string>:2, in create_engine(url, **kwargs)

File ~/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py:281, in deprecated_params.<locals>.decorate.<locals>.warned(fn, *args, **kwargs)
    274     if m in kwargs:
    275         _warn_with_version(
    276             messages[m],
    277             versions[m],
    278             version_warnings[m],
    279             stacklevel=3,
    280         )
--> 281 return fn(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py:550, in create_engine(url, **kwargs)
    546 u = _url.make_url(url)
    548 u, plugins, kwargs = u._instantiate_plugins(kwargs)
--> 550 entrypoint = u._get_entrypoint()
    551 _is_async = kwargs.pop(\"_is_async\", False)
    552 if _is_async:

File ~/.local/lib/python3.10/site-packages/sqlalchemy/engine/url.py:758, in URL._get_entrypoint(self)
    756 else:
    757     name = self.drivername.replace(\"+\", \".\")
--> 758 cls = registry.load(name)
    759 # check for legacy dialects that
    760 # would return a module with 'dialect' as the
    761 # actual class
    762 if (
    763     hasattr(cls, \"dialect\")
    764     and isinstance(cls.dialect, type)
    765     and issubclass(cls.dialect, Dialect)
    766 ):

File ~/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:372, in PluginLoader.load(self, name)
    370     if impl.name == name:
    371         self.impls[name] = impl.load
--> 372         return impl.load()
    374 raise exc.NoSuchModuleError(
    375     \"Can't load plugin: %s:%s\" % (self.group, name)
    376 )

File /usr/local/lib/python3.10/importlib/metadata/__init__.py:171, in EntryPoint.load(self)
    166 \"\"\"Load the entry point from its definition. If only a module
    167 is indicated by the value, return that module. Otherwise,
    168 return the named object.
    169 \"\"\"
    170 match = self.pattern.match(self.value)
--> 171 module = import_module(match.group('module'))
    172 attrs = filter(None, (match.group('attr') or '').split('.'))
    173 return functools.reduce(getattr, attrs, module)

File /usr/local/lib/python3.10/importlib/__init__.py:126, in import_module(name, package)
    124             break
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File ~/.local/lib/python3.10/site-packages/snowflake/sqlalchemy/__init__.py:30
     10     import importlib.metadata as importlib_metadata
     12 from sqlalchemy.types import (
     13     BIGINT,
     14     BINARY,
   (...)
     27     VARCHAR,
     28 )
---> 30 from . import base, snowdialect
     31 from .custom_commands import (
     32     AWSBucket,
     33     AzureContainer,
   (...)
     42     PARQUETFormatter,
     43 )
     44 from .custom_types import (
     45     ARRAY,
     46     BYTEINT,
   (...)
     61     VARIANT,
     62 )

File ~/.local/lib/python3.10/site-packages/snowflake/sqlalchemy/base.py:13
     11 from sqlalchemy.sql import compiler, expression
     12 from sqlalchemy.sql.elements import quoted_name
---> 13 from sqlalchemy.util.compat import string_types
     15 from .custom_commands import AWSBucket, AzureContainer, ExternalStage
     16 from .util import _set_connection_interpolate_empty_sequences

ImportError: cannot import name 'string_types' from 'sqlalchemy.util.compat' (/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py)"
}
```
### Description

When trying to connect to a DB with the SQLDatabase module, I get the error as shown.

### System Info

sqlalchemy-2.0.27
langchain-community 0.0.20
langchain 0.1.5

**Comment by keenborder786** [comment] 2024-02-16 20:02
@Abe410  I have been able to replicate the error at my machine. Seems to be a version mismatch problem. Will get back to you.

**Comment by keenborder786** [comment] 2024-02-16 20:39
@Abe410 The error is become of mismatch between sqlalchemy and snowflake-connector versions. 

The `snowflake-sqlalchemy` latest version 1.5.1 do not currently supports sqlalchemy versions >=2.0, which is a raised issue at their github: https://github.com/snowflakedb/snowflake-sqlalchemy/issues/380.

Therefore you will have to downgrade the version of your sqlalchemy to less <2.0. I tried using `1.4.51`. However then the problem is that their is slight import problem in the langchain current `sql_database` module which is not compatible with sqlalchemy version <2.0. But for that I have created a PR so that should be fixed. 

So ideally once my PR is merged, you should be able to make it work with following versions of sqlalchemy and snowflake-connector:
```
- sqlalchemy==1.4.51
- snowflake-sqlalchemy==1.5.1
```

**Comment by Abe410** [comment] 2024-02-16 20:52
> @Abe410 The error is become of mismatch between sqlalchemy and snowflake-connector versions.
> 
> The `snowflake-sqlalchemy` latest version 1.5.1 do not currently supports sqlalchemy versions >=2.0, which is a raised issue at their github: [snowflakedb/snowflake-sqlalchemy#380](https://github.com/snowflakedb/snowflake-sqlalchemy/issues/380).
> 
> Therefore you will have to downgrade the version of your sqlalchemy to less <2.0. I tried using `1.4.51`. However then the problem is that their is slight import problem in the langchain current `sql_database` module which is not compatible with sqlalchemy version <2.0. But for that I have created a PR so that should be fixed.
> 
> So ideally once my PR is merged, you should be able to make it work with following versions of sqlalchemy and snowflake-connector:
> 
> ```
> - sqlalchemy==1.4.51
> - snowflake-sqlalchemy==1.5.1
> ```

Thank you for the help.

I am getting the SQLDatabase chain error now with sqlalchemy==1.4.49.

Also, once the fix is merged, how long does it take to get published on Pypi?

**Comment by Abe410** [comment] 2024-02-20 22:01
> @Abe410 The error is become of mismatch between sqlalchemy and snowflake-connector versions.
> 
> The `snowflake-sqlalchemy` latest version 1.5.1 do not currently supports sqlalchemy versions >=2.0, which is a raised issue at their github: [snowflakedb/snowflake-sqlalchemy#380](https://github.com/snowflakedb/snowflake-sqlalchemy/issues/380).
> 
> Therefore you will have to downgrade the version of your sqlalchemy to less <2.0. I tried using `1.4.51`. However then the problem is that their is slight import problem in the langchain current `sql_database` module which is not compatible with sqlalchemy version <2.0. But for that I have created a PR so that should be fixed.
> 
> So ideally once my PR is merged, you should be able to make it work with following versions of sqlalchemy and snowflake-connector:
> 
> ```
> - sqlalchemy==1.4.51
> - snowflake-sqlalchemy==1.5.1
> ```

So currently I have Langchain 0.1.8, and sqlachemy 1.4.51. But I get the following error:

```
Traceback (most recent call last):
    from langchain.agents import AgentExecutor, Tool
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain/agents/__init__.py", line 34, in <module>
    from langchain_community.agent_toolkits import (
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/agent_toolkits/__init__.py", line 46, in <module>
    from langchain_community.agent_toolkits.sql.base import create_sql_agent
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/agent_toolkits/sql/base.py", line 29, in <module>
    from langchain_community.agent_toolkits.sql.toolkit import SQLDatabaseToolkit
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/agent_toolkits/sql/toolkit.py", line 9, in <module>
    from langchain_community.tools.sql_database.tool import (
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/tools/sql_database/tool.py", line 33, in <module>
    class QuerySQLDataBaseTool(BaseSQLDatabaseTool, BaseTool):
  File "/home/airflow/.local/lib/python3.10/site-packages/langchain_community/tools/sql_database/tool.py", line 47, in QuerySQLDataBaseTool
    ) -> Union[str, Sequence[Dict[str, Any]], Result[Any]]:
TypeError: 'type' object is not subscriptable
```

**Comment by keenborder786** [comment] 2024-02-27 20:17
@Abe410  can you please close this issue.

**Closed** 2024-02-27 20:18 UTC
Labels: 🤖:bug
