### ISSUE TITLE
No module named 'langchain_core' - Langchain in Vertex AI

### ISSUE THREAD

**Issue by maryshgh** [langchain-ai/langchain#23838] opened 2024-07-03 19:34 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import langchain

### Error Message and Stack Trace (if applicable)

No module named 'langchain_core' 

### Description

Starting this morning we are getting different kind of errors while trying to use langchain in Vertex AI, not quite sure what is the root of problem, Google or Langchain.

### System Info

Python 3.10.12

**Comment by efriis** [comment] 2024-07-03 19:37
Hello! Could you confirm you have the dependency installed? In order to import things from langchain, you'll have to `pip install langchain`

**Comment by efriis** [comment] 2024-07-03 19:38
oh actually I'm going to close this. This seems to be an issue in the hosted Google Vertex AI product, and not the open source library.

If you can reproduce this in a local environment, happy to take a look!

**Closed by efriis** 2024-07-03 19:38 UTC
Labels: 🔌: google

**Comment by maryshgh** [comment] 2024-07-03 19:45
Thank you for your response, I installed it, now I'm getting the following error: 

cannot import name 'create_model' from 'langchain_core_runnables.utils'

it happens when it tries to import the following:
from langchain.agents import AgentExecuter

**Comment by maryshgh** [comment] 2024-07-03 19:48
Btw, we have been using langchain packages in Vertex AI and never had this issue before, (package not found error), could this be a bug in Vertex AI?

**Comment by efriis** [comment] 2024-07-03 19:56
Could be! We don't have a package `langchain_core_runnables` (maybe this is the module within core `langchain_core.runnables`), and it should be `AgentExecutor` with an o instead

Would try to debug it with whichever infrastructure provider you're using!

**Comment by maryshgh** [comment] 2024-07-03 20:00
Oh yes, sorry for typos, I am not able to use GitHub in my work laptop, so I wrote the errors myself, apparently there were some typos, :D

**Comment by averikitsch** [comment] 2024-07-03 20:37
Hi @maryshgh, This most likely is an issue with the LangChain on VertexAI deployment. Can you ask this question in https://github.com/googleapis/python-aiplatform with the code snippet you are trying to run? Thanks!

**Comment by maryshgh** [comment] 2024-07-03 20:46
@averikitsch thank you, I'll try that.
