### ISSUE TITLE
DOC: some import statement of Oracle Cloud Infrastructure Generative AI can be improved

### ISSUE THREAD

**Issue by shukawam** [langchain-ai/langchain#17156] opened 2024-02-07 05:00 UTC
### Issue with current documentation:

There is a point of improvement in the import statement included in the following sample code that exists in the Usage.

> from langchain_community.llms import OCIGenAI

```py
from langchain_community.llms import OCIGenAI

# use default authN method API-key
llm = OCIGenAI(
    model_id="MY_MODEL",
    service_endpoint="https://inference.generativeai.us-chicago-1.oci.oraclecloud.com",
    compartment_id="MY_OCID",
)

response = llm.invoke("Tell me one fact about earth", temperature=0.7)
print(response)
```

This is a point as well.

> from langchain_community.vectorstores import FAISS

```py
from langchain.schema.output_parser import StrOutputParser
from langchain.schema.runnable import RunnablePassthrough
from langchain_community.embeddings import OCIGenAIEmbeddings
from langchain_community.vectorstores import FAISS
```

### Idea or request for content:

The first item is appropriate to do this.

```py
from langchain_community.llms.oci_generative_ai import OCIGenAI
```

And the second item is appropriate to do this.

```py
from langchain_community.vectorstores.faiss import FAISS
```

**Comment by PennlaineChu** [comment] 2024-02-13 04:13
I have changed the document, however, both the original code and the code you provided works in my case. Can you explain what the problem is with the existing module, please?

**Comment by baskaryan** [comment] 2024-02-13 06:38
Yea not clear what the improvement is. Closing issue for now but feel free to re-open if i'm missing something @shukawam

**Closed by baskaryan** 2024-02-13 06:38 UTC
Labels: auto:documentation, area: models
