### ISSUE TITLE
Anthropic Upgrade issue

### ISSUE THREAD

**Issue by btconway** [langchain-ai/langchain#7056] opened 2023-07-02 17:44 UTC
### System Info

Langchain version 0.0.221
Anthropic versions 0.3.1 and 0.3.2

Whenever using ChatAnthropic, this now appears. Version 0.2.10 works, but the below error appears since the Anthropic update a couple of days ago

`Anthropic.__init__() got an unexpected keyword argument 'api_url' (type=type_error)`

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use ChatAnthropic in any form with the latest version of Anthropic and you will encounter: "Anthropic.__init__() got an unexpected keyword argument 'api_url' (type=type_error)"

### Expected behavior

It should work if the API key is provided. You should not have to specify a URL.

**Comment by devstein** [comment] 2023-07-02 17:55
Duplicate of #6883

**Closed** 2023-10-08 16:05 UTC
Labels: auto:bug
