### ISSUE TITLE
ValueError(f"Could not parse LLM output: `{llm_output}`")

### ISSUE THREAD

**Issue by chun1617** [langchain-ai/langchain#1477] opened 2023-03-06 19:34 UTC
`  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\chains\base.py", line 268, in run
    return self(kwargs)[self.output_keys[0]]
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\chains\base.py", line 168, in __call__
    raise e
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\chains\base.py", line 165, in __call__
    outputs = self._call(inputs)
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 406, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 102, in plan
    action = self._get_next_action(full_inputs)
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\agents\agent.py", line 64, in _get_next_action
    parsed_output = self._extract_tool_and_input(full_output)
  File "C:\Program Files\Python\Python310\lib\site-packages\langchain\agents\conversational\base.py", line 84, in _extract_tool_and_input
    raise ValueError(f"Could not parse LLM output: `{llm_output}`")
ValueError: Could not parse LLM output: `Thought: Do I need to use a tool? Yes
Action: Use the requests library to write a Python code to do a post request
Action Input:

```
import requests

url = 'https://example.com/api'
data = {'key': 'value'}

response = requests.post(url, data=data)

print(response.text)
```

``

**Comment by mrbende** [comment] 2023-03-08 03:03
I am receiving a very similar response...

```
127.0.0.1 - - [07/Mar/2023 21:54:37] "OPTIONS /chat HTTP/1.1" 200 -
Message received: Please start a conversation with me!


> Entering new AgentExecutor chain...
127.0.0.1 - - [07/Mar/2023 21:54:39] "POST /chat HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/reedbender/Repositories/Praxis/pria/app.py", line 78, in chat
    response = agent_executor.run(message)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/agents/agent.py", line 503, in _call
    next_step_output = self._take_next_step(
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/agents/agent.py", line 406, in _take_next_step
    output = self.agent.plan(intermediate_steps, **inputs)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/agents/agent.py", line 102, in plan
    action = self._get_next_action(full_inputs)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/agents/agent.py", line 64, in _get_next_action
    parsed_output = self._extract_tool_and_input(full_output)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/agents/mrkl/base.py", line 138, in _extract_tool_and_input
    return get_action_and_input(text)
  File "/Users/reedbender/.pyenv/versions/3.9.15/lib/python3.9/site-packages/langchain/agents/mrkl/base.py", line 46, in get_action_and_input
    raise ValueError(f"Could not parse LLM output: `{llm_output}`")
ValueError: Could not parse LLM output: `Sure, I'd be happy to chat with you! Is there anything specific you'd like to talk about or any questions you have?`
```

It seems that the ChatGPT api is handling the request, but something in the langchain parsing of the output is breaking. Any ideas? Thanks for these developments!

**Comment by RoySadaka** [comment] 2023-03-08 07:08
It is possible that this is caused due to the nature of the current implementation, which puts all the prompts into the user role in ChatGPT.
I ran into the same issue when using the SQL agent.
To debug it, i took the text that is being sent to the LLM, but manually broke it down to ChatGPT messages style,
meaning, to the system role I've added the agent definition, followed by the user role with the "begin! and question" part, followed by the assistant role with the "Thought" part,
this resulted in a proper output that can be parsed.

It is plausible to assume that if/when the code will be updated to support chat format with system/user/assistant roles, in these agents, it will work again, until then, we can still use the (really good) davinchi model.

Thanks team!

**Comment by sidedwards** [comment] 2023-03-08 07:58
Super hacky, but I appended `" The response should include the prefix 'AI: <response>'."` and that resolved some of my prompts that were breaking. 🤷

**Comment by jnorris441** [comment] 2023-03-09 03:29
Sometimes the LLM ignores the instructions on the format which breaks the entire thing...like it clearly says the last line should be "Final Answer: " but if it comes back without that you are in trouble. 

I hope the new chat messages format will eliminate the need to parse the reply text

**Comment by jpdus** [comment] 2023-03-09 19:43
I have the same problem, amplified by a SystemMessage in German. The model often forgets the correct tokens for Tool usage or the final answer, resulting in the parsing error.

Has anyone an example where all the prompts (at least the descriptions, not necessarily the tokens) for an Agent and the Tools are translated, so the model can't get confused between multiple languages?

**Comment by jnorris441** [comment] 2023-03-10 07:29
I like Microsoft's tweak on the agent instructions, maybe it works better:

```
VISUAL_CHATGPT_FORMAT_INSTRUCTIONS = """To use a tool, please use the following format:

Thought: Do I need to use a tool? Yes
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action

When you have a response to say to the Human, or if you do not need to use a tool, you MUST use the format:

Thought: Do I need to use a tool? No
{ai_prefix}: [your response here]

"""
```

https://github.com/microsoft/visual-chatgpt/blob/main/visual_chatgpt.py#L51

**Comment by skylacking04** [comment] 2023-03-10 11:36
> It is possible that this is caused due to the nature of the current implementation, which puts all the prompts into the user role in ChatGPT. I ran into the same issue when using the SQL agent. To debug it, i took the text that is being sent to the LLM, but manually broke it down to ChatGPT messages style, meaning, to the system role I've added the agent definition, followed by the user role with the "begin! and question" part, followed by the assistant role with the "Thought" part, this resulted in a proper output that can be parsed.
> 
> It is plausible to assume that if/when the code will be updated to support chat format with system/user/assistant roles, in these agents, it will work again, until then, we can still use the (really good) davinchi model.
> 
> Thanks team!

can you show the code for that?

**Comment by claust** [comment] 2023-03-15 19:06
This can happen if the model does not follow the given instructions. In most of the cases I have seen, it would proabably be better to simply return the output instead of throwing a `ValueError` when the output cannot be parsed according to the instructions. I will test this strategy further and maybe make a PR.

**Comment by libratiger** [comment] 2023-03-21 11:44
It seem that because the LLM response with text start with "Thought", but the regex match code in langchain does not consider this.

**Comment by FJGEODEV** [comment] 2023-03-22 18:19
Is there any solution to this? Thanks.

**Comment by alexprice12** [comment] 2023-03-23 05:41
I tried to dig into a solution for this. It can be for a myriad for reasons it looks like. Basically, the model is not obeying the prompt.

At the minimum, I think agent code should ask the model for a well-structure response that adhere to the prompt.

**Comment by libratiger** [comment] 2023-03-23 07:06
but the model may do not adopt your request. @alexprice12 

this is about standard

**Comment by alexprice12** [comment] 2023-03-23 11:37
When the model asks for a tool that doesn't exist, langchain tells the model that the tool they chose doesn't exist.

I'm open to more than one solution. What are you thinking is the best approach here?

**Comment by tomsib2001** [comment] 2023-03-23 23:23
I hope it's not too silly an idea, and looking at the code I'm not sure where such an intervention would take place, but:
How about, instead of raising the error

```python
        raise ValueError(f"Could not parse LLM output: `{llm_output}`")
```
, the answer given by the llm was sent back to it complaining that it does not have the right format, and asking it to comply with it?

**Comment by tiagoefreitas** [comment] 2023-03-24 05:23
Duplicate of https://github.com/hwchase17/langchain/issues/1358

**Comment by rishibh7** [comment] 2023-04-01 05:35
any solution yet?

**Comment by Willis75** [comment] 2023-05-26 00:57
check this, worked for me:
https://python.langchain.com/en/latest/modules/agents/agent_executors/examples/handle_parsing_errors.html

**Comment by gprabhuv4me** [comment] 2023-07-28 20:26
I have tried above option but got the below error.

OutputParserException: Could not parse LLM output: `Same issue as before. We need to run this command in a Jupyter notebook or in a terminal.
Action: None`

**Comment by zaldivards** [comment] 2023-11-03 01:22
Surrounding the tool's output with quotes worked for me:

```python
def my_calc(expr: str) -> str:
    """
    Some custom tool

    Evaluate the provided arithmetic expression in Python syntax.

    Example: my_calc("2+2")
    Result: 4
    """
    expr = re.sub(r"[^0-9+\-*/().]", "", expr)
    return f'"{eval(expr)}"' # surrounding the output
```

**Comment by nameless0704** [comment] 2024-01-31 07:22
I'm still getting this error on version 0.1.4 using open-source LLM Qwen-14B-Chat model. Is it still a thing?

**Closed** 2024-05-08 16:03 UTC
