### ISSUE TITLE
Prompt variables are not replaced for tool calling agents when using SystemMessage class

### ISSUE THREAD

**Issue by Dakes** [langchain-ai/langchain#22486] opened 2024-06-04 17:34 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain.globals import set_debug
from langchain_core.messages import SystemMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI

set_debug(True)

prompt_string = """\
Test prompt
first: {first_value}
second: {second_value}
"""

prompt = ChatPromptTemplate.from_messages([
    SystemMessage(content=prompt_string),  # buggy: using this, the variables are not replaced
    # ("system", prompt_string),  # working as expected
    ("user", "{user_input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])

llm = ChatOpenAI(model="gpt-3.5-turbo")


@tool
def dummy_tool(input: str):
    """
    It doesn't do anything useful. Don't use.
    """
    return input


tools = [dummy_tool]

agent = create_tool_calling_agent(llm=llm, tools=tools, prompt=prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, max_iterations=3)

prompt_input = {
    "first_value": "Because 42 is the answer to ",
    "second_value": "the ultimate question of life, the universe, and everything.",
    "user_input": "Why 42?",
}
run = agent_executor.invoke(input=prompt_input)
print(run)
```

### Description

Hello everybody. 🖖
I noticed the class `SystemMessage` doesn't work for replacing prompt variables. But using just `("system", "{variable}")` works as expected, even though, according to the documentation, both should be identical. 

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Sat, 25 May 2024 20:20:51 +0000
> Python Version:  3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417]

Package Information
-------------------
> langchain_core: 0.2.3
> langchain: 0.2.1
> langchain_community: 0.2.1
> langsmith: 0.1.67
> langchain_minimal_example: Installed. No version info available.
> langchain_openai: 0.1.8
> langchain_pinecone: 0.1.1
> langchain_text_splitters: 0.2.0
> langgraph: 0.0.60

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by keenborder786** [comment] 2024-06-04 21:38
No it is not a bug, you need to use `SystemMessagePromptTemplate` instead of `SystemMessage`.  The difference between `SystemMessagePromptTemplate` and `SystemMessage` is that in the latter, you are not giving a template that can be filled later but are defining the final message that will be accepted by your chat model.
```python

set_debug(True)

prompt_string = """\
Test prompt
first: {first_value}
second: {second_value}
"""

prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template(prompt_string),  # This will work same as ("system", prompt_string)
    # ("system", prompt_string),  # working as expected
    ("user", "{user_input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad"),
])


```

**Comment by Dakes** [comment] 2024-06-04 21:47
I see, thanks for clarifying. I think I tried before with just an llm, no agent. And there it replaced the variables successfully, even with SystemMessage. So that confused me a bit and is why I assumed it is a bug.

**Comment by keenborder786** [comment] 2024-06-05 02:50
@Dakes if you are happy, please close the issue.

**Closed** 2024-06-07 18:04 UTC
Labels: Ɑ: agent, 🤖:bug, 🔌: openai
