### ISSUE TITLE
"NoIndexException: Index not found when initializing Chroma from a persisted directory"

### ISSUE THREAD

**Issue by murasz** [langchain-ai/langchain#3011] opened 2023-04-17 10:21 UTC
I am facing a problem when trying to use the Chroma vector store with a persisted index. I have already loaded a document, created embeddings for it, and saved those embeddings in Chroma. The script ran perfectly with LLM and also created the necessary files in the persistence directory (.chroma\index). The files include:

chroma-collections.parquet
chroma-embeddings.parquet
id_to_uuid_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.pkl
index_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.bin
index_metadata_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.pkl
uuid_to_id_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.pkl

However, when I try to initialize the Chroma instance using the persist_directory to utilize the previously saved embeddings, I encounter a NoIndexException error, stating "Index not found, please create an instance before querying".

Here is a snippet of the code I am using in a Jupyter notebook:

```
# Section 1
import os
from langchain.vectorstores import Chroma
from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain

# Load environment variables
%reload_ext dotenv
%dotenv info.env
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# Section 2 - Initialize Chroma without an embedding function
persist_directory = '.chroma\\index'
db = Chroma(persist_directory=persist_directory)

# Section 3
# Load chat model and question answering chain
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=.5, openai_api_key=OPENAI_API_KEY)
chain = load_qa_chain(llm, chain_type="stuff")

# Section 4
# Run the chain on a sample query
query = "The Question - Can you also cite the information you give after your answer?"
docs = db.similarity_search(query)
response = chain.run(input_documents=docs, question=query)
print(response)
```
Please help me understand what might be causing this problem and suggest possible solutions. Additionally, I am curious if these pre-existing embeddings could be reused without incurring the same cost for generating Ada embeddings again, as the documents I am working with have lots of pages. Thanks in advance!

**Comment by bkamapantula** [comment] 2023-04-17 12:28
You may have to use `db.persist()` after `db = Chroma(...)` in Section 2.

**Comment by murasz** [comment] 2023-04-17 14:24
> 

Still the same error: NoIndexException: Index not found, please create an instance before querying

In Section 2 after loading the embeddings: Using embedded DuckDB with persistence: data will be stored in: .chroma\index
No embedding_function provided, using default embedding function: SentenceTransformerEmbeddingFunction

**Comment by KeshavSingh29** [comment] 2023-04-18 08:46
I'm facing the same issue, even after using db.persist( ) and creating the index files. Some issue with langchain wrapper?

**Comment by KeshavSingh29** [comment] 2023-04-18 08:47
I'm facing the same issue, even after using db.persist( ) and creating the index files. Some issue with langchain wrapper?

**Comment by murasz** [comment] 2023-04-18 15:50
That's quite awkward. I think the problem is directly linked with Langchain's chroma wrapper. There must be some changes in the source code, maybe. @hwchase17 what do you think?

**Comment by bowu** [comment] 2023-04-19 05:44
I encountered the same problem.

`db = Chroma(persist_directory="./vdb", embedding_function=embeddings)
    retriever = db.as_retriever()
    qa = RetrievalQAWithSourcesChain.from_chain_type(llm=OpenAI(), retriever=retriever)
    result = qa({"question": req.message}, return_only_outputs=True)`

**Comment by KurtFeynmanGodel** [comment] 2023-04-19 06:33
> I am facing a problem when trying to use the Chroma vector store with a persisted index. I have already loaded a document, created embeddings for it, and saved those embeddings in Chroma. The script ran perfectly with LLM and also created the necessary files in the persistence directory (.chroma\index). The files include:
> 
> chroma-collections.parquet chroma-embeddings.parquet id_to_uuid_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.pkl index_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.bin index_metadata_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.pkl uuid_to_id_3508d87c-12d1-4bbe-ae7f-69a0ec3c6616.pkl
> 
> However, when I try to initialize the Chroma instance using the persist_directory to utilize the previously saved embeddings, I encounter a NoIndexException error, stating "Index not found, please create an instance before querying".
> 
> Here is a snippet of the code I am using in a Jupyter notebook:
> 
> ```
> # Section 1
> import os
> from langchain.vectorstores import Chroma
> from langchain.chat_models import ChatOpenAI
> from langchain.chains.question_answering import load_qa_chain
> 
> # Load environment variables
> %reload_ext dotenv
> %dotenv info.env
> OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
> 
> # Section 2 - Initialize Chroma without an embedding function
> persist_directory = '.chroma\\index'
> db = Chroma(persist_directory=persist_directory)
> 
> # Section 3
> # Load chat model and question answering chain
> llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=.5, openai_api_key=OPENAI_API_KEY)
> chain = load_qa_chain(llm, chain_type="stuff")
> 
> # Section 4
> # Run the chain on a sample query
> query = "The Question - Can you also cite the information you give after your answer?"
> docs = db.similarity_search(query)
> response = chain.run(input_documents=docs, question=query)
> print(response)
> ```
> 
> Please help me understand what might be causing this problem and suggest possible solutions. Additionally, I am curious if these pre-existing embeddings could be reused without incurring the same cost for generating Ada embeddings again, as the documents I am working with have lots of pages. Thanks in advance!

adding the embedding_function to the chroma call worked for me. 
`db = Chroma(persist_directory=persist_directory, embedding_function=embeddings)`
IF you are using your own collection however, you might need to manually assign the collection to the db as it seems to use the default "langchain" or create a duplicate collection. 
`db._collection=db._client.get_collection("custom-collection")`

I'm new to python so verify.

**Comment by jeffchuber** [comment] 2023-04-19 06:38
Hi everyone, Jeff from Chroma here. I will be looking into this tomorrow morning and will report back.

**Comment by murasz** [comment] 2023-04-19 11:44
h

> Hi everyone, Jeff from Chroma here. I will be looking into this tomorrow morning and will report back.

Hi Jeff,
I noticed your message on ChromaD's repository. If you need anything else beyond the code I shared, please let me know. I may also send you the created bin and pk files via email.

Just to update you, the first code I used to convert txt files from PDF, divide them into chunks, and create embeddings worked perfectly. I was able to get answers without any problems. However, when I tried to use the whole embedded data again, I encountered the error message "NoIndexException: Index not found when initializing Chroma from a persisted directory."

My main concern is that I don't want to embed the data each time before answering a question. The reason is that processing large PDFs could end up costing a lot in the long term and would not be cost-effective for my purposes. Therefore, I'm open to any solutions you may have.

Let me know if you need any additional information or if you have any suggestions.

**Comment by murasz** [comment] 2023-04-19 11:48
> My main concern is that I don't want to embed the data each time before answering a question. The reason is that processing large PDFs could end up costing a lot in the long term and would not be cost-effective for my purposes. Therefore, I'm open to any solutions you may have.
> 
> Let me know if you need any additional information or if you have any suggestions.



> 

@KurtFeynmanGodel My main concern is that I don't want to embed the data each time before answering a question. The reason is that processing large PDFs could end up costing a lot in the long term and would not be cost-effective for my purposes. Therefore, I'm open to any solutions you may have.

Let me know if you need any additional information or if you have any suggestions.

**Comment by jeffchuber** [comment] 2023-04-19 18:58
here is a trivial example based on the langchain example `vectorstore.ipynb`

`test.py`
```python
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter

from langchain.document_loaders import TextLoader
loader = TextLoader('../../../state_of_the_union.txt')
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
state_of_union_store = Chroma.from_documents(texts, embeddings, collection_name="state-of-union", persist_directory=".chromadb/")

val = state_of_union_store.similarity_search("the", top_n=2)
print(val)
```

`test2.py`
```python
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma

embeddings = OpenAIEmbeddings()
state_of_union_store = Chroma(collection_name="state-of-union", persist_directory=".chromadb/", embedding_function=embeddings)

val = state_of_union_store.similarity_search("the", top_n=2)
print(val)
```

This works on my end. Can others try this?

**Comment by murasz** [comment] 2023-04-19 22:23
Dear

> here is a trivial example based on the langchain example `vectorstore.ipynb`
> 
> `test.py`
> 
> ```python
> from langchain.embeddings.openai import OpenAIEmbeddings
> from langchain.vectorstores import Chroma
> from langchain.text_splitter import CharacterTextSplitter
> 
> from langchain.document_loaders import TextLoader
> loader = TextLoader('../../../state_of_the_union.txt')
> documents = loader.load()
> text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
> texts = text_splitter.split_documents(documents)
> 
> embeddings = OpenAIEmbeddings()
> state_of_union_store = Chroma.from_documents(texts, embeddings, collection_name="state-of-union", persist_directory=".chromadb/")
> 
> val = state_of_union_store.similarity_search("the", top_n=2)
> print(val)
> ```
> 
> `test2.py`
> 
> ```python
> from langchain.embeddings.openai import OpenAIEmbeddings
> from langchain.vectorstores import Chroma
> 
> embeddings = OpenAIEmbeddings()
> state_of_union_store = Chroma(collection_name="state-of-union", persist_directory=".chromadb/", embedding_function=embeddings)
> 
> val = state_of_union_store.similarity_search("the", top_n=2)
> print(val)
> ```
> 
> This works on my end. Can others try this?

Dear @jeffchuber I am still facing the same issue even after making some changes to the code as per your previous suggestion. Therefore, I would like to send you the .ipynb files via email along with a brief description of the process. This way, you can review the files and possibly find a solution that will work reliably. Once we have a solution, we can share it with the community. Thank you for your help.

**Comment by jeffchuber** [comment] 2023-04-19 22:23
ok sounds great! please send that along via email or discord DM

**Comment by murasz** [comment] 2023-04-19 22:58
> ok sounds great! please send that along via email or discord DM

Ok Email sent. (hello@trychroma.com). Thank you so much!

**Comment by jeffchuber** [comment] 2023-04-20 04:39
In everyone, if you are using a notebook -- you need to call `client.persist()` manually because the garbage collection in a notebook does not call the  `__del__` lifecycle method on the object. 

I just added a PR here to improve our docs on this. https://github.com/chroma-core/docs/pull/44

**Comment by KeshavSingh29** [comment] 2023-04-20 04:48
@jeffchuber Thanks for this. It solved the issue for me.

**Comment by murasz** [comment] 2023-04-20 09:52
> 

Thank you @jeffchuber  for the proposed solution. Unfortunately, it gave me the same error. I've emailed you regarding this issue.

Let me share the Jupyter notebook codebase here again:

```
# Section 1
import os
from langchain.vectorstores import Chroma
from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain
from langchain.embeddings.openai import OpenAIEmbeddings

# Load environment variables
%reload_ext dotenv
%dotenv info.env
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
```
```
# Section 2 - Initialize Chroma with the persisted directory and the embedding function
persist_directory = '.chroma/'
embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)
db = Chroma(collection_name="letstry", persist_directory=".chromadb/", embedding_function=embeddings)
db.persist()  # Add this line
```
```
# Section 3
# Load chat model and question answering chain
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=.6, openai_api_key=OPENAI_API_KEY)
chain = load_qa_chain(llm, chain_type="stuff")
```
```
#Section 4
# Run the chain on a sample query
query = "What is Harga transport?"
docs = db.similarity_search(query)
response = chain.run(input_documents=docs, question=query)
print(response)
```

**Comment by KurtFeynmanGodel** [comment] 2023-04-20 12:27
@murasz I started off with the same problem of no index found but I cannot remember how I got over that. Can you make sure your persist directory is correct? Now I encounter a different problem. When initializing from the index, if I do not pass in an embedding function, it warns 
`No embedding_function provided, using default embedding function: SentenceTransformerEmbeddingfFunction` 
and then after it initializes the database when trying to retrieve it says there is a dimentionality mismatch in the embeddings

`Dimensionality of (384) does not match with index dimensionality (1024)`

So it seems hnswlib.py, which I assume is responsible for the dimensionality check, uses the defaulted embedding_function to get an embedding dimension number which it checks against the embedding database as a constraint before retrieval. As a result, without having a thorough look at the code, it would seem like including the embedding_function when restoring from an index might not recompute embeddings from the collection (which I understand is your major concern) but rather just check dimensionality as a constraint. It certainly seems that way from how fast the database gets restored when I initialize with the embedding_function.

@jeffchuber Any insights?

**Comment by jeffchuber** [comment] 2023-04-21 15:51
@KurtFeynmanGodel yes - I can help with this. 

Chroma relies on the user to tell it how to embed things. This is not currently stored within chroma, which is why you have to pass it to Chroma whenever you do `create_collection`, `get_collection`, or `get_or_create_collection`.

What is happening here is that Chroma is using the default embedding function (`sentence-transformers`) to embed your document/query with `384` dimensionality. As this does not match the dimensionality of the embedding model you use `1024` - it throws an error.

**Comment by saginawj** [comment] 2023-04-26 19:18
Hi @jeffchuber  and team.  Not sure if this issue is still being worked or if it's considered resolved, but I'm running into the same issues as the rest of the thread.

I'm using an AWS-hosted Chroma instance with persistence, and I can store & retrieve successfully in the same notebook.

But when I switch to a new notebook (eventually to be replaced by a web app) I can instantiate the AWS Chroma instance but receive what appears to be a very similar issue. 

`Exception: {"error":"NoIndexException('Index not found, please create an instance before querying')"}`

I use db.persist() as advised, but still doesn't seem to work in a separate notebook.

**Comment by Valdanitooooo** [comment] 2023-04-28 07:13
The same issue was resolved on my Ubuntu server by restarting my python app :smile:

**Comment by klisfer** [comment] 2023-05-06 14:36
Hi @jeffchuber @murasz , I found the issue. So the issue is with the uuid creation and fetching. The issue of index not found was only happening in the case of custom collection_name. So you guys have used this mechanism to create uuid for the saved index files : uuid.uuid4(), which generates and gets a new uuid every time it is called.

ref file : chromadb/db/clickhouse.py , chromadb/db/duckdb.py

![image](https://user-images.githubusercontent.com/11735995/236630363-eb7efc16-958a-4bdd-af6b-20a3c4340d58.png)


I instead changed the uuid mechanism while creating and fetching docs to do something like this using a seed as collection_name parameter which generates a consistent uuid for a fixed value of collection_name.

```
   rd = random.Random()
   rd.seed(collection_name)
   id = uuid.UUID(int=rd.getrandbits(128))

   collection_uuid = id
```


This generates a consistent UUID for a collection based on the name passed in the params. Do this same in get_collection_uuid_from_name() functions as well . 

I tried this in various scenarios where it was failing for me, this solution works in those scenarios.

**Comment by dankolesnikov** [comment] 2023-05-29 23:40
I am facing the same issue, I am using a notebook to create a persisted chroma db instance locally and then copy the data over to the server, my file structure is:

<img width="198" alt="CleanShot 2023-05-29 at 16 39 18@2x" src="https://github.com/hwchase17/langchain/assets/10562358/d01c0e87-8a2d-4ce1-a33a-258e9c62cf8e">

the file with the following code is on the same level as the db folder:
```
persist_directory = 'db'
embedding = OpenAIEmbeddings()
chroma_client = Chroma(persist_directory=persist_directory,
                       embedding_function=embedding)
```

what could be the bug here?

**Comment by jeffchuber** [comment] 2023-05-30 17:07
@dankolesnikov did you create the Chroma DB outside LangChain and now you want to pass to LangChain?

**Comment by dankolesnikov** [comment] 2023-05-30 17:55
@jeffchuber Sorry I forgot to update my thread. I was able to resolve this error simply by upgrading chroma! I am not facing this error anymore but I uncovered another one and created a ticket on chroma's repo: https://github.com/chroma-core/chroma/issues/640

Please look into it if possible, I owe you and Anton a beer if it is something that I overlooked.

**Comment by dankolesnikov** [comment] 2023-05-30 17:56
@murasz  can you try upgrading chromadb/langchain packages? if it works for you we could close this issue

**Comment by jeffchuber** [comment] 2023-05-30 17:58
@dankolesnikov great! glad to hear it. will take a look at 640

**Comment by Badrul-Goomblepop** [comment] 2023-06-01 15:46
Not sure if it worked for @murasz but I can report that upgrading langchain ( `pip install --upgrade langchain`) worked for me.

**Comment by murasz** [comment] 2023-06-01 17:18
I haven't checked it yet due to my intensive schedule this week. Unless you  won't let me check till monday, you can close the topic.

**Comment by lastrei** [comment] 2023-06-02 10:41
@jeffchuber 
could you help me with these code , i create a api with fastapi and langchain,there is a problem, i upload 3 documents ,and in another py file , i use vectorstore.get() ,i can see all the document, but when i close the api, i use vectorstore.get() again, there is only the first document return , and i found that ,when i close the api,The size of the file chroma-embeddings.parquet has decreased，Its size has become the size of the first document uploaded for the first time？why？thanks
```
import os
import re
import uuid

from fastapi import FastAPI, UploadFile
import uvicorn
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
import chromadb

app = FastAPI()

DB_DIR = "./db"
embeddings = HuggingFaceEmbeddings(model_name="nghuyong/ernie-3.0-medium-zh")


def replace_newlines_and_spaces(text):
    # Replace all newline characters with spaces
    text = text.replace("\n", " ")
    # Replace multiple spaces with a single space
    text = re.sub(r'\s+', ' ', text)
    return text


def get_documents(file_path):
    return TextLoader(file_path, encoding="utf-8").load()


def init_chromadb(file_path):
    if not os.path.exists(DB_DIR):
        os.mkdir(DB_DIR)

    documents = []
    for num, doc in enumerate(get_documents(file_path)):
        doc.page_content = replace_newlines_and_spaces(doc.page_content)
        documents.append(doc)

    client_settings = chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=DB_DIR,
        anonymized_telemetry=False
    )
    # Split the documents into chunks
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=20, length_function=len,
                                                   separators=["\n\n", "\n", " ", "", "。"])
    texts = text_splitter.split_documents(documents)
    print(len(texts))
    # Create the vectorestore to use as the index
    vectorstore = Chroma.from_documents(texts, embeddings, persist_directory=DB_DIR, client_settings=client_settings,
                                        collection_name="news")
    vectorstore.persist()


@app.post("/process-file")
async def process_file(file: UploadFile):
    try:
        random_name = str(uuid.uuid1())
        index_path = "./upload_file/" + random_name + "/"
        file_path = index_path + file.filename
        if not os.path.exists("./upload_file/" + random_name):
            os.mkdir("./upload_file/" + random_name)
        with open(file_path, "wb") as buffer:
            buffer.write(file.file.read())

        init_chromadb(file_path)

        return {"status": "success"}
    except Exception as e:
        return {"status": "failure", "error": str(e)}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=7777)
```

**Comment by jeffchuber** [comment] 2023-06-02 21:42
@lastrei 

This is because you are creating a new Chroma Client every time and the auto-lifecycle cleanup is running in reverse order and saving the first one you created last - which results in a stomp.

A solution here is to creating one chroma client, and then pass it into Langchain when you want to use it. 

Here is a small example. 

```
import chromadb
chroma_client = chromadb.Client()
collection = chroma_client.create_collection(name="my_collection")

collection.add(
    documents=["This is a document", "This is another document"],
    metadatas=[{"source": "my_source"}, {"source": "my_source"}],
    embeddings=[[1,2,3],[4,5,6]],
    ids=["id1", "id2"]
)

from langchain.vectorstores import Chroma
langchainChroma = Chroma(client=chroma_client, collection_name="my_collection") 

print(langchainChroma._collection.count())
```

You can pass this directly `from_documents` - https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/chroma.py#LL417C10-L417C10

**Comment by lastrei** [comment] 2023-06-03 02:05
> collection_name

thanks！ i get it！

**Comment by tnwei** [comment] 2023-07-16 10:54
Reading this thread from start to end, my understanding is that the root cause is Chroma doesn't reinitialize `collection_name` to `langchain` when restored from a persisted directory, and so passing `collection_name = "langchain"` or whatever manual name was given to it should resolve this error. Feel free to correct me if I'm wrong

**Comment by mhovgaard** [comment] 2023-07-19 15:38
I have had the same problem - when I reload the persisted database via the class init (Chroma), it is non-functional (does not throw any error codes) - but cannot return any documents. When I use reloading via the _from_documents, it works.  The collection parameters does no difference.

**Comment by jeffchuber** [comment] 2023-07-19 17:38
@mhovgaard happy to help more here - please ask in our discord - https://discord.gg/MMeYNTmh3x - we are responding very quickly right now

**Closed** 2023-10-25 16:09 UTC
