### ISSUE TITLE
I am getting this error 

### ISSUE THREAD

**Issue by KomalVardhanL-Hexaware** [langchain-ai/langchain#22811] opened 2024-06-12 11:27 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied to create extension "vector"
HINT:  Must be superuser to create this extension.

[SQL: BEGIN;SELECT pg_advisory_xact_lock(1573678846307946496);CREATE EXTENSION IF NOT EXISTS vector;COMMIT;]
(Background on this error at: https://sqlalche.me/e/20/f405)

### Error Message and Stack Trace (if applicable)

ERROR:Failed to create vector extension: (psycopg2.errors.InsufficientPrivilege) permission denied to create extension "vector"
HINT:  Must be superuser to create this extension.

[SQL: BEGIN;SELECT pg_advisory_xact_lock(1573678846307946496);CREATE EXTENSION IF NOT EXISTS vector;COMMIT;]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-06-12,16:45:07 start_local:828 - ERROR:Exception on /codebits/api/v1/parse [POST]

### Description

ERROR:Failed to create vector extension: (psycopg2.errors.InsufficientPrivilege) permission denied to create extension "vector"
HINT:  Must be superuser to create this extension.

[SQL: BEGIN;SELECT pg_advisory_xact_lock(1573678846307946496);CREATE EXTENSION IF NOT EXISTS vector;COMMIT;]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-06-12,16:45:07 start_local:828 - ERROR:Exception on /codebits/api/v1/parse [POST]

### System Info

<img width="733" alt="Screenshot 2024-06-12 at 4 55 43 PM" src="https://github.com/langchain-ai/langchain/assets/108388565/74ce6f4f-491c-41b0-98f6-e0859745aa5a">
MAC
python 3.12

**Comment by eyurtsev** [comment] 2024-06-12 14:14
@KomalVardhanL-Hexaware It's a permissions issue:

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied to create extension "vector"
HINT: Must be superuser to create this extension.

Whomeever is administering the database needs to add the pgvector extension.

**Comment by eyurtsev** [comment] 2024-06-12 14:15
This is not a bug so closing the issue. Please use QA discussions for usage questions.

**Comment by eyurtsev** [comment] 2024-06-12 14:15
cc @pprados (in case you're if you're interested to improve the UX with better error messages)

**Closed by eyurtsev** 2024-06-12 14:15 UTC

**Comment by KomalVardhanL-Hexaware** [comment] 2024-06-13 05:23
But I am the owner of the DB
