### ISSUE TITLE
get_openai_callback doesn't work with create_openai_functions_agent (it returns 0 used tokens / dollars)

### ISSUE THREAD

**Issue by lamparelli** [langchain-ai/langchain#18212] opened 2024-02-27 18:09 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

This is the code that reproduces the issue.
```
tools = [
    # a series of tools
]

llm = ChatOpenAI(model='gpt-3.5-turbo-0125')

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    MessagesPlaceholder(variable_name="chat_history"),
    ("user", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad")
])

memory = ConversationBufferMemory(
    return_messages=True,
    memory_key="chat_history", 
    output_key='output',
)

# with this, get_openai_callback works (but returns a deprecation warning)
agent_good = OpenAIFunctionsAgent(llm=llm, tools=tools, prompt=prompt)

# with this, get_openai_callback does NOT work properly (it prints zero used tokens)
agent_bad = create_openai_functions_agent(llm=llm, tools=tools, prompt=prompt)

agent_executor = AgentExecutor(
    agent=agent_bad, # if I use agent_good, the cost is calculated properly
    tools=tools, 
    verbose=False, 
    memory=memory, 
    return_intermediate_steps=True
)

with get_openai_callback() as cb:
    result = agent_executor.invoke({'input': 'Hi'})
    print(result)
    print(cb)
```

### Description

If I use OpenAIFunctionsAgent to create an agent, I get a deprecation warning, telling me to use create_openai_functions_agent instead.

But, as of langchain 0.1.9 if I use create_openai_functions_agent to create an agent, the OpenAI callback to track costs stops working properly (it returns 0 used tokens and 0 dollars cost).

### System Info

```
python==3.10
tiktoken==0.6.0
openai==1.12.0
langchain==0.1.9
langchain-core==0.1.27
langchain-community==0.0.24
langchain-openai==0.0.8
pydantic==2.6.2
chromadb==0.4.23
```

**Comment by keenborder786** [comment] 2024-02-27 18:35
@lamparelli Interesting, I have been able to reproduce the issue. Let me see and get back to you.

**Comment by keenborder786** [comment] 2024-02-27 20:14
Yeap the reason why this is happening because the `AgentExecutor` uses `RunnableAgent` when you create a agent using `create_openai_functions_agent`. And if you see the the [plan](https://github.com/langchain-ai/langchain/blob/733367b7954b9bb6c89ba150154e4f942a337a06/libs/langchain/langchain/agents/agent.py#L382) method of `RunnableAgent` which is invoked by AgentExecutor, you will see that it calls the underlying `RunnableSequence` using `stream` method which in turn also calls the `ChatOpenAI` [_stream](https://github.com/langchain-ai/langchain/blob/733367b7954b9bb6c89ba150154e4f942a337a06/libs/partners/openai/langchain_openai/chat_models/base.py#L408). This hits the following [Chat Chunk Completion Object Endpoint of OpenAI](https://platform.openai.com/docs/api-reference/chat/streaming) whose response object does not contain any information about token usage unlike the [Chat Completion Object Endpoint](https://platform.openai.com/docs/api-reference/chat/object). Consequently, getting the token usage information is impossible.

The only turnaround to this is that you overwrite the `plan` method of RunnableAgent and use that Agent and this works for me.

```python

class CustomRunnableAgent(RunnableAgent):
    def plan(
        self,
        intermediate_steps,
        callbacks,
        **kwargs
    ):
        inputs = {**kwargs, **{"intermediate_steps": intermediate_steps}}
        output = self.runnable.invoke(inputs, config={"callbacks": callbacks})
        return output
tools = [WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())]

llm = ChatOpenAI(model='gpt-3.5-turbo-0125')

prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful agent"),
    MessagesPlaceholder(variable_name="chat_history"),
    ("user", "{input}"),
    MessagesPlaceholder(variable_name="agent_scratchpad")
])

memory = ConversationBufferMemory(
    return_messages=True,
    memory_key="chat_history", 
    output_key='output',
)

# with this, get_openai_callback works (but returns a deprecation warning)
agent_good = OpenAIFunctionsAgent(llm=llm, tools=tools, prompt=prompt)

# with this, get_openai_callback does NOT work properly (it prints zero used tokens)
agent_bad = create_openai_functions_agent(llm=llm, tools=tools, prompt=prompt)

agent_executor = AgentExecutor(
    agent=CustomRunnableAgent(runnable = agent_bad), # if I use agent_good, the cost is calculated properly
    tools=tools, 
    verbose=False, 
    memory=memory, 
    return_intermediate_steps=True
)

with get_openai_callback() as cb:
    result = agent_executor.invoke({'input': 'Hi'})
    print(result)
    print(cb)

```

**Comment by keenborder786** [comment] 2024-02-27 20:14
If this works for  you, please close the issue.

**Comment by lamparelli** [comment] 2024-02-28 08:44
@keenborder786 Hi, I've tried your code, and the "work-around" works. 
But, creating an OpenAI Agent and tracking costs is a pretty basic functionality that should work out of the box for an LLM framework.
Since the official function advised by Langchain for creating agents breaks the cost tracking, I feel like this is something that deserves a fix in a next release, more than the issue being closed with a workaround and the "bug" still being left in the code.
How can I make the devs aware of the issue?

**Comment by RustamIbragimov** [comment] 2024-03-14 14:52
I very much agree with @lamparelli. This is a breaking change and doesn't seem like it works as intended if everyone needs to implement the work around.

**Comment by eyurtsev** [comment] 2024-03-15 14:36
duplicate of: https://github.com/langchain-ai/langchain/issues/16798

patch available here: https://github.com/langchain-ai/langchain/pull/18761 as of release 0.1.12

**Closed by eyurtsev** 2024-03-15 14:36 UTC
Labels: Ɑ: agent, 🤖:bug, 🔌: openai

**Comment by gryshko** [comment] 2024-03-18 08:02
I am using the Pandas data frame agent, which I believe was not patched yet, and `stream_runnable` is not passed to agent from `kwargs`. I 'fix' that with 
```
agent_executor.agent.stream_runnable = False
```
I thought it might help someone. For clarity, you need to update it to at least 0.1.12 to have it working.

**Comment by axtsoi** [comment] 2024-04-03 04:13
@eyurtsev The current workaround doesn't work for create_sql_agent which is a toolkit type. Can you please provide a fix for this as well? I agreed with most users - token counting is one of the fundamental and crucial features by LangChain but this doesn't seem to be treated as a high priority. @hwchase17 Thanks. Please help the community.
