### ISSUE TITLE
Indexing API slow

### ISSUE THREAD

**Issue by AIApprentice101** [langchain-ai/langchain#11935] opened 2023-10-17 17:36 UTC
### System Info

I compared the speed of indexing with and without using the Indexing API, and I notice a significant difference. Using Indexing API is 30-50% slower. Also for experiment, I tried to index the exact same data twice, and the Indexing API is taking extremely long time for the second time. Any help would be appreciated. Thank you.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

With Indexing API:
```
vdb = PGVector(
            connection_string,
            collection_name,
            embedding_function
        )
record_manager = SQLRecordManager(
    namespace, engine=postgres_engine
)
record_manager.create_schema()
index(
    doc_chunks,
    record_manager,
    vdb,
    cleanup=None,
    source_id_key="source",
)
```

Without Indexing API:
```
vdb = PGVector.from_texts(
                texts
                embedding
                collection_name
                connection_string
            )
```

### Expected behavior

I expect the speeds are comparable with/without Indexing API.

**Comment by eyurtsev** [comment] 2023-10-18 02:00
@AIApprentice101 interesting. Could you provide a bit more context, do you have benchmark times? Where are the databases located with respect to the indexing code -- are they remote / are they local? What batch sizes are being used? The indexing API on the 2nd time will skip indexing into the destination db, but it'll still need to update records in the record manager. Still it should probably be faster since it shuold be able to skip the embedding step entirely if the underlying content hasn't changed.

**Comment by AIApprentice101** [comment] 2023-10-18 12:58
@eyurtsev Thank you for your reply. I think I figure out the problem. 

Some benchmark: indexing the 1st time takes 15 sec.

So if I use `SQLite` as the record manager, the duplicated docs are indexed pretty fast (as you mentioned, they are all skipped). It takes 4 sec.

If I use `Postgres` as the record manager (by using `record_manager = SQLRecordManager(engine=create_engine(postgrs_url))`, indexing duplicated docs takes 90 sec.

**Comment by AIApprentice101** [comment] 2023-10-19 19:11
@eyurtsev Here's the skeleton code I used to create index. I have a Postgres hosted in a server. The data is very small, 200 entries, each with around 500 characters. 

I use default settings for postgres engine. Can you advise what I can change to make it work faster? Thank you.

```
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from langchain.embeddings import HuggingFaceInstructEmbeddings

url = URL.create(
    drivername="postgresql+psycopg2",
    username="dummy",
    host="dummy",
    database="dummy",
    password="dummy"
)
engine = create_engine(url, connect_args={'connect_timeout': 5})
embedding_function = HuggingFaceInstructEmbeddings(...)

collection_name = "dummy"
vdb = PGVector(
            connection_string,
            collection_name,
            embedding_function
        )
record_manager = SQLRecordManager(
    namespace, engine=engine
)
record_manager.create_schema()

# index first time
index(
    doc_chunks,
    record_manager,
    vdb,
    cleanup=None,
    source_id_key="source",
)
# index second time (duplicate)
index(
    doc_chunks,
    record_manager,
    vdb,
    cleanup=None,
    source_id_key="source",
)
```

**Comment by eyurtsev** [comment] 2023-10-19 21:22
Great! The code looks OK, nothing obvious at that level...

1) Are you able to reproduce with a local postgres service running via docker compose?
2) What's the time difference between index first time and index second time?
3) To confirm, you're not re-generating the doc_chunks the second time around? (i.e., no time is spent generating docs)
4) Could you eliminate the round trip times to the postgres service as a confounding variable? i.e., how many requests are made to postgres + what is round trip time? `batch_size` is 100, how many doc_chunks do you have?

**Comment by AIApprentice101** [comment] 2023-10-19 23:11
@eyurtsev Thank you for then instructions. Your instinct is pinpoint. When I use local-hosted postgres, the second index is super fast. I think the issue is from the diff between local and remote postgres servers. Can you provide me some insights if there's any setting for the remote postgres that I can tweak? I use a managed service on GCP. 

On the side note, the first-time indexing time is comparable using local vs remote postgres servers. The difference is only on the second (duplicate) indexing. Is it related to the upsertion_record table? 

Thank you.

**Comment by mescanne** [comment] 2023-12-01 11:50
Hello -

I think the problem is here:
https://github.com/langchain-ai/langchain/blob/b161f302ff56a14d8d0331cbec4a3efa23d06e1a/libs/langchain/langchain/indexes/_api.py#L306

Looking at the logs from SQLAcademy I can see:
- Efficient pulling out of existing keys (one query per batch)
- Efficient updating of final status (one query per batch)
- One query per key for updating of timestamp (this loop)

As a remote database is more latency sensitive, doing a single query per row will be horribly slow. Turning this into a single call to record_manager update should make this super-fast. (Possibly with some batch tuning)

**Comment by mescanne** [comment] 2023-12-01 13:57
I've created a fix for the above. The existing unit tests exercise the code against sqlite, and I've tested it locally with postgresql (I encountered the same issue, so I've seen dramatic performance improvements).

**Comment by eyurtsev** [comment] 2024-02-14 03:47
Fix got merged and another similar fix was added to the async variant. Closing issue as complete.

**Closed by eyurtsev** 2024-02-14 03:47 UTC
Labels: area: embeddings, area: vector store, auto:bug
