### ISSUE TITLE
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context'

### ISSUE THREAD

**Issue by Bengt** [langchain-ai/langchain#15508] opened 2024-01-03 23:11 UTC
### System Info

Full traceback:

```
File "/src/app.py", line 9, in <module>
    from langchain.chains import ConversationalRetrievalChain
  File "/venv/lib/python3.11/site-packages/langchain/chains/__init__.py", line 20, in <module>
    from langchain.chains.api.base import APIChain
  File "/venv/lib/python3.11/site-packages/langchain/chains/api/base.py", line 11, in <module>
    from langchain.callbacks.manager import (
  File "/venv/lib/python3.11/site-packages/langchain/callbacks/__init__.py", line [45] in <module>
    from langchain_core.tracers.context import (
ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (/venv/lib/python3.11/site-packages/langchain_core/tracers/context.py)
```

### Who can help?

@hwchase17 @agola

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This issue seems to originate from the import:

```
from langchain.chains import ConversationalRetrievalChain
```

### Expected behavior

The modules should import successfully.

**Comment by Bengt** [comment] 2024-01-03 23:15
Here is another traceback leading to the same issue:

```
tests/app/conftest.py:3: in <module>
    from llm_chatbot.src.app import create_app
llm_chatbot/src/app.py:9: in <module>
    from langchain.chains import ConversationalRetrievalChain
venv/lib/python3.10/site-packages/langchain/chains/__init__.py:20: in <module>
    from langchain.chains.api.base import APIChain
venv/lib/python3.10/site-packages/langchain/chains/api/base.py:11: in <module>
    from langchain.callbacks.manager import (
venv/lib/python3.10/site-packages/langchain/callbacks/__init__.py:[45](https://gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot/-/jobs/5855473173#L45): in <module>
    from langchain_core.tracers.context import (
E   ImportError: cannot import name 'tracing_enabled' from 'langchain_core.tracers.context' (/1-llm-chatbot/venv/lib/python3.10/site-packages/langchain_core/tracers/context.py)
````

**Comment by Bengt** [comment] 2024-01-04 11:02
Downgrading to 0.0.349 worked around this issue for me. Hence, this seems to be a regression since 0.0.350.

**Comment by baskaryan** [comment] 2024-01-04 13:41
If you bump to `langchain>=0.0.354` that should also fix it

**Comment by baskaryan** [comment] 2024-01-04 13:42
Duplicate of #15526

**Closed by baskaryan** 2024-01-04 13:42 UTC
Labels: auto:bug, area: models, integration: aws

**Comment by Bengt** [comment] 2024-01-04 20:29
Can confirm, 0.0.354 fixes this issue for me.
