### ISSUE TITLE
AzureOpenAIEmbeddings cannot authenticate with azure_ad_token_provider

### ISSUE THREAD

**Issue by proschowsky** [langchain-ai/langchain#14402] opened 2023-12-07 15:35 UTC
### System Info

Langchain: 0.0.346
OpenAI:  1.3.7

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Simple script to authenticate to Azure with RBAC

```
from langchain.embeddings import AzureOpenAIEmbeddings
from azure.identity import DefaultAzureCredential, get_bearer_token_provider

token_provider = get_bearer_token_provider(DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default")
embeddings = AzureOpenAIEmbeddings(azure_endpoint='xxxxxxx', azure_ad_token_provider=token_provider)
```

### Expected behavior

Should authenticate, but is seems like the `azure_ad_token_provider` is not added to the values dict

langchain/embeddings/azure_openai.py line 80-86
```
values["azure_endpoint"] = values["azure_endpoint"] or os.getenv(
            "AZURE_OPENAI_ENDPOINT"
        )
values["azure_ad_token"] = values["azure_ad_token"] or os.getenv(
            "AZURE_OPENAI_AD_TOKEN"
        )
```
Other parameters are added to values, but not `azure_ad_token_provider`

**Comment by proschowsky** [comment] 2023-12-12 07:40
Still present in 0.0.349

`KeyError: 'azure_ad_token_provider'`

Traceback:
```
.....
File "...lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "...lib/python3.11/site-packages/pydantic/v1/main.py", line 1102, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
File "...lib/python3.11/site-packages/langchain_community/embeddings/azure_openai.py", line 139, in validate_environment
    "azure_ad_token_provider": values["azure_ad_token_provider"],
                               ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by darioxz** [comment] 2023-12-12 09:00
@proschowsky It seems the issue has only been resolved in the AzureOpenAI class of `chat_models`. We need to bring in https://github.com/langchain-ai/langchain/pull/14166/files which should fix this issue.

**Closed** 2023-12-13 22:37 UTC
Labels: area: embeddings, auto:bug

**Comment by axen22** [comment] 2023-12-18 08:16
Has this been committed ? version 0.0.350 still holds error "  KeyError: 'azure_ad_token_provider' "

**Comment by 169** [comment] 2023-12-18 08:27
@axen22 Langchain has not released a new version yet, but I feel it should be released soon.

**Comment by 169** [comment] 2023-12-19 01:04
@axen22 @proschowsky Good news, a new version is released and can be updated using `pip install langchain==v0.0.351`

**Comment by proschowsky** [comment] 2023-12-19 06:36
> @axen22 @proschowsky Good news, a new version is released and can be updated using `pip install langchain==v0.0.351`

Great. I have just verified that it is working with our code and Azure setup.

**Comment by axen22** [comment] 2023-12-19 09:29
@proschowsky  I still get this for v 0.0.351 . Have you updated any other version eg. openai etc ?
<img width="1123" alt="image" src="https://github.com/langchain-ai/langchain/assets/53572480/84fc9bab-e740-4dba-8277-755ca9763637">

**Comment by hangingman** [comment] 2024-03-21 08:21
There are two `_bearer_token_provider.py` in azure-identity.
One is sync, another one is async.

- `azure/identity/_bearer_token_provider.py`
- `azure/identity/aio/_bearer_token_provider.py`

In my case, using updated langchain , the problem is resolved. I'm using sync version `azure/identity/_bearer_token_provider.py`.
