### ISSUE TITLE
Structured output using ChatOllama with nested schemas

### ISSUE THREAD

**Issue by julian24bas** [langchain-ai/langchain#25343] opened 2024-08-13 12:34 UTC
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from typing import Optional, List
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama import ChatOllama


class Person(BaseModel):
    """Information about a person."""

    # ^ Doc-string for the entity Person.
    # This doc-string is sent to the LLM as the description of the schema Person,
    # and it can help to improve extraction results.

    # Note that:
    # 1. Each field is an `optional` -- this allows the model to decline to extract it!
    # 2. Each field has a `description` -- this description is used by the LLM.
    # Having a good description can help improve extraction results.
    name: Optional[str] = Field(default=None, description="The name of the person")
    hair_color: Optional[str] = Field(
        default=None, description="The color of the person's hair if known"
    )
    height_in_meters: Optional[str] = Field(
        default=None, description="Height measured in meters"
    )


class Data(BaseModel):
    """Extracted data about people."""

    # Creates a model so that we can extract multiple entities.
    people: List[Person]


# Define a custom prompt to provide instructions and any additional context.
# 1) You can add examples into the prompt template to improve extraction quality
# 2) Introduce additional parameters to take context into account (e.g., include metadata
#    about the document from which the text was extracted.)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are an expert extraction algorithm. "
            "Only extract relevant information from the text. "
            "If you do not know the value of an attribute asked to extract, "
            "return null for the attribute's value.",
        ),
        # Please see the how-to about improving performance with
        # reference examples.
        # MessagesPlaceholder('examples'),
        ("human", "{text}"),
    ]
)

llm = ChatOllama(model="llama3.1", temperature=0)

runnable = prompt | llm.with_structured_output(schema=Data)

text = "Alan Smith is 6 feet tall and has blond hair. Alan Poe is 3 feet tall and has grey hair."
response = runnable.invoke({"text": text})
print(response)

```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "<project_directory>/tmp_extraction_setup.py", line 59, in <module>
    response = runnable.invoke({"text": text})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/runnables/base.py", line 2878, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/output_parsers/base.py", line 183, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/runnables/base.py", line 1785, in _call_with_config
    context.run(
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/runnables/config.py", line 427, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/output_parsers/base.py", line 184, in <lambda>
    lambda inner_input: self.parse_result(
                        ^^^^^^^^^^^^^^^^^^
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/output_parsers/abc_tools.py", line 300, in parse_result
    raise e
  File "<virtual_env_directory>/lib/python3.11/site-packages/xyz_core/output_parsers/abc_tools.py", line 295, in parse_result
    pydantic_objects.append(name_dict[res["type"]](**res["args"]))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<virtual_env_directory>/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Data
people
  value is not a valid list (type=type_error.list)

Process finished with exit code 1

### Description

I followed the [tutorial](https://python.langchain.com/v0.1/docs/use_cases/extraction/how_to/examples/) using ChatOllama from langchain-ollama and model with tool support like llama3.1 to run it. This works fine when using the class `Person` to retrieve the information. However when changing the `schema` to `Data` I get the error above.

The data which is passed to the pydantic model has this pattern:
`{'people': '[{"name": "Alan Smith", "height": "6 feet", "hair color": "blond"}, {"name": "Alan Poe", "height": "3 feet", "hair color": "grey"}]'}`

As you can see here the keys for hair color and height in meters are false. Also the value for `'people'` is a string rather than a list. So there is definitely a problem with the `Data` class using another pydantic class as attribute.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
> Python Version:  3.11.7 (main, Jan 24 2024, 11:32:46) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.2.29
> langchain: 0.2.12
> langchain_community: 0.2.11
> langsmith: 0.1.98
> langchain_ollama: 0.1.1
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.2
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> jsonpatch: 1.33
> numpy: 1.26.4
> ollama: 0.3.1
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> typing-extensions: 4.12.2

**Comment by corbinklett** [comment] 2024-08-13 13:33
Related, I've noticed that the new `json_schema` method with ChatOpenAI's `with_structured_output` does not support nested `TypedDict` schemas, and I have also not gotten it to work with Pydantic schemas yet. 

You also cannot specify which fields are `Required` versus `NotRequired` when using a TypedDict.

**Comment by ishaan-upadhyay** [comment] 2024-10-16 17:48
Hello! We are a group of 4 students at the University of Toronto who would be interested in looking into this issue if possible. Can confirm that this is still reproducible in the latest version of Langchain, including replacement of the Pydantic imports in the sample code. 

Other team members: @mirajismail @TheDannyG @ZackSteine

**Comment by TheDannyG** [comment] 2024-11-02 03:44
Hello, we have identified the cause of the issue and have created a temporary solution. 

In summary: the issue is cause by the Ollama model returning the tool call arguments as a string, which is not parsed by the Ollama integration. This is solved in the OpenAI integration by having parsing at the `_generate` level.

<details>
<summary>Detailed Root Cause</summary>

The `with_structured_output` function is not implemented in the Ollama integration, so it defaults to the superclass `BaseChatModel` implementation. This implementation recognizes various schema types and selects an appropriate output parser. It also sets up tool calling to get the structured output from the model using the `bind_tool` method. Since the schema passed to `with_structured_output` is a Pydantic class, it correctly chooses the Pydantic output parser. The model’s output (trimmed to the relevant section) is as follows (this was generated through an API call to Ollama, but the response structure is the same within Langchain). The issue can be observed under the `people` key, where the value is a string representing the list of `Person` objects. The response is passed into the Pydantic output parser, which attempts to pass the string into the constructor of the `Data` class. This causes an exception due to the Pydantic class enforcing strict typing of its attributes.
  
```json
  "message": {
      "role": "assistant",
      "content": "",
      "tool_calls": [
          {
              "function": {
                  "name": "Data",
                  "arguments": {
                      "people": "[{\"height\": \"6 feet\", \"hair_color\": \"blond\"}, {\"height\": \"3 feet\", \"hair_color\": \"grey\"}]"
                  }
              }
          }
      ]
  }
  ```
  
For comparison, we can examine the model output (also trimmed to the relevant section) from the OpenAI Langchain integration, which does not suffer from this bug. This helps clarify what the Pydantic parser expects. The following was observed while debugging/tracing the example code from the issue when using OpenAI. 
  
  ```python
  tool_calls=[
      {
          'name': 'Data', 
          'args': {
              'people': [
                  {
                      'name': 'Alan Smith', 
                      'hair_color': 'blond', 
                      'height_in_meters': '1.83'
                  }, 
                  {
                      'name': 'Alan Poe', 
                      'hair_color': 'grey', 
                      'height_in_meters': '0.91'
                  }
              ]
          }, 
          'id': 'call_wD8hExz6oJEr5vuckSZWlzLg', 
          'type': 'tool_call'
      }
  ]
  ```
  
As a side note, the OpenAI model also provides the arguments as a string, verified by calling the OpenAI API directly. This shows that the issue can be fixed in Langchain and is not inherently a problem with the model. Doing some research into this issue, Ollama has two open issues related to this: [Issue 1](https://github.com/ollama/ollama/issues/6155) and [Issue 2](https://github.com/ollama/ollama/issues/6377). One commenter mentioned that this is done to maintain compatibility with the OpenAI API. It’s unclear whether supporting deeply nested tool calls will be expected in future releases, so this issue is likely better handled within Langchain.

The OpenAI integration solves this problem within the [`_generate`](https://github.com/langchain-ai/langchain/blob/3b0b7cfb7455c973e73dbd00a42fda65a33a9286/libs/partners/openai/langchain_openai/chat_models/base.py#L680) function in the `BaseChatOpenAI` class, which is the private function responsible for generating the model output. This function calls another private function, `_create_chat_result`, which creates the `ChatResult` from the model response. `_create_chat_result` calls [`_convert_dict_to_message`](https://github.com/langchain-ai/langchain/blob/3b0b7cfb7455c973e73dbd00a42fda65a33a9286/libs/partners/openai/langchain_openai/chat_models/base.py#L745), which includes a section that handles tool calls. For each tool call, [`parse_tool_call`](https://github.com/langchain-ai/langchain/blob/3b0b7cfb7455c973e73dbd00a42fda65a33a9286/libs/core/langchain_core/output_parsers/openai_tools.py#L18C1-L68C18) is invoked. This function deserializes the arguments using `json.loads`. This is where the string, which causes the exception in the Ollama integration, is converted to a dictionary in the OpenAI integration, and thus allowing the Pydantic parser to process it.
</details>


For a temporary solution, the following can be done (generalized so that it can be applied to tool calling outside just structured output). Some additional error handling may be needed.
``` python
class OllamaFixParser(BaseOutputParser[AIMessage]):
    def parse_tool_call(self, tool_call: dict):
        new_args = tool_call["args"]
        for key, val in new_args.items():
            if isinstance(val, str):
                try:
                    new_args[key] = json.loads(val)
                except json.JSONDecodeError:
                    continue
        tool_call["args"] = new_args
        return tool_call

    def parse_result(self, result: list[ChatGeneration], *, partial: bool = False) -> Any:
        for gen in result:
            mes = gen.message
            tool_calls = mes.tool_calls
            mes.tool_calls = [self.parse_tool_call(tool_call) for tool_call in tool_calls]
        return result[0].message
    
    def parse(self, text: str) -> Any:
        return self.parse_result([Generation(text=text)])

llm_tools = llm.bind_tools([Data], tool_choice="any")
ollama_fix_parser = OllamaFixParser()
py_parser = PydanticToolsParser(tools=[cast(TypeBaseModel, Data)], first_tool_only=True)
llm_with_structured_output = llm_tools | ollama_fix_parser | py_parser

runnable = prompt | llm_with_structured_output
```

---

## Solution
For a more permanent solution, we have intially identified two main approaches, parsing either at the `bind_tools` level, or parsing at the `_generate` level. The approach at the `bind_tools` level has lower impact on the code base as compared with `_generate` which is called on all invocations of Ollama models. However, it would not be as universal of a solution as the `_generate` approach as used in the OpenAI integration. We would love feedback on the best approach for solving this issue.

**Comment by ishaan-upadhyay** [comment] 2024-11-06 23:02
@ccurme Hello! 

Before we proceed with fixing this bug, our team would like to make sure we're aligned on a good approach for a solution.

For a bit more detail on our proposed approach (and after some more discussion):
- We can parse in  [`_get_tool_calls_from_response`](https://github.com/langchain-ai/langchain/blob/ea0ad917b0911521e3ec7c973babb945fec115d9/libs/partners/ollama/langchain_ollama/chat_models.py#L63) which already exists and is called in the relevant areas for the Ollama integration. To compare, the OpenAI integration uses [`_create_chat_result`](https://github.com/langchain-ai/langchain/blob/ea0ad917b0911521e3ec7c973babb945fec115d9/libs/partners/openai/langchain_openai/chat_models/base.py#L745), [`_convert_dict_to_message`](https://github.com/langchain-ai/langchain/blob/ea0ad917b0911521e3ec7c973babb945fec115d9/libs/partners/openai/langchain_openai/chat_models/base.py#L123) and [`parse_tool_call`
](https://github.com/langchain-ai/langchain/blob/ea0ad917b0911521e3ec7c973babb945fec115d9/libs/core/langchain_core/output_parsers/openai_tools.py#L18) for the parsing.
- We've dropped the `bind_tools` approach (misunderstanding of the data flow). Other approaches may involve modifying core code (e.g. modifying `with_structured_output`) which we would like to avoid.

Please let us know if you have any further input or if there's anyone else we should ask (including partner teams from the Ollama side), We thought you would be the most appropriate person to initially ping since you had self-assigned this issue. 

---

As an aside - this is unrelated to the fix for Ollama specifically - for the [`test_structured_output_...` series of standard integration tests](https://github.com/langchain-ai/langchain/blob/ea0ad917b0911521e3ec7c973babb945fec115d9/libs/standard-tests/langchain_standard_tests/integration_tests/chat_models.py#L336), we're uncertain if nested schemas should be used for the base `Joke` class (to be reused across all the integration tests), or if this should be placed into a separate test case. 

If we could get some input on this as well, that'd be great. Thank you!

**Comment by MagMueller** [comment] 2024-11-08 14:01
Thanks for working on this.

I have deep nested schemas which work fine for e.g. gpt-4o, but break for qwen2.5:32b-instruct. I set an my pydantic schema, 
```python
llm = ChatOllama(
	model='qwen2.5:32b-instruct',
	base_url='http://localhost:11434',
	temperature=0,
	format='json',
)
``` 
....

```python
structured_llm = self.llm.with_structured_output(Output, include_raw=True)
response = await structured_llm.ainvoke(
	input_messages
)
``` 
For e.g. gpt-4o it directly gives back my pydantic. For qwen2.5:32b-instruct it does not parse the json. Even the raw message is the correct json. 
From the second message on, the raw output does not even have the correct dict. Its just empty.

Can this happen - because the model is not smart enough? I thought with logit boosting one can just force the model to output the right keys.

**Comment by TheDannyG** [comment] 2024-11-13 02:52
Hello @MagMueller, 

Sorry for the slow response. 

I also am experiencing issues when running the example in the [mentioning issue](https://github.com/gregpr07/browser-use/issues/5#issuecomment-2460635560) when running with `qwen2.5:32b-instruct` or `llama3-groq-tool-use:8b`. Please refer to this [gist](https://gist.github.com/TheDannyG/e6d58dfedfa1a36e94fe7fb0af0a0bef) for the tool call JSONs and the exceptions.

These problems seem to stem from a different issue from the one in the original issue. The Qwen2.5 models does not return the tool calling argument values as strings like the Ollama and OpenAI APIs specify. The tool calls are returned directly as JSON objects, and as such they are not affected by the original issue. However, this JSON does not match the Output Pydantic class, as the `current_state.memory` key is an empty dictionary. 

When running with `llama3-groq-tool-use:8b`, the issue is similar. The returned tool calls has an empty dictionary for the `current_state` key.

I will investigate further, but I am currently leaning towards it either being an issue with the models, or a distinct bug in the Ollama integration.

Are these the same kind of issues you encountered? Would it be possible to get an example program that encounters these issues, alongside exceptions/model outputs?

**Comment by ccurme** [comment] 2024-11-13 20:55
Thank you for the detail in these comments!

Ollama generally returns parsed tool calls, but if I'm understanding correctly it seems like this parsing does not extend to nested schemas.

@TheDannyG @ishaan-upadhyay adding additional checks / parsing in [_get_tool_calls_from_response](https://github.com/langchain-ai/langchain/blob/ea0ad917b0911521e3ec7c973babb945fec115d9/libs/partners/ollama/langchain_ollama/chat_models.py#L63) makes sense to me, assuming we do it in a safe way (i.e., if parsing fails we have a good fallback). As I understand the only cases where behavior will change are currently failing.

Regarding testing: OK to add an Ollama-specific test to `integration_tests/test_chat_models.py` if we want (it can be a normal test function outside the standard test suite). Adding to standard tests is also an option if most tested models can consistently pass it -- that is, failures should almost always be due to preventable issues with library logic, instead of model limitations.

**Comment by MagMueller** [comment] 2024-11-17 16:24
For me the strange thing is that it works sometimes, like here in the first step: [browser-use local model](https://github.com/gregpr07/browser-use/issues/5#issuecomment-2473067312).
But in the second step, it outputs incorrect keys, which can not get parsed, so the output is just None.

Could it be, that some models are just too small and not capable of remembering how the output should be?

**Comment by kongsynft** [comment] 2024-11-25 23:16
this solution worked perfectly for me while trying to use the `Plan(BaseModel)` from the attached image [of this tutorial](https://langchain-ai.github.io/langgraph/tutorials/plan-and-execute/plan-and-execute/#define-the-state), while using `llama3.2` instead of `gpt-4o`.

big thanks for your help, i can confirm it works perfectly and i hope they include one of your two suggested fixes into the next version. the sooner the better!

![image](https://github.com/user-attachments/assets/811f8172-1021-46fa-8438-6c71cd0788c8)

**Closed** 2024-11-27 15:32 UTC
Labels: 🤖:bug, investigate, Ɑ: parsing
